@extends('layouts.web')
@section('title', 'Yasaklı Ürünler - Exxefy')


@section('content')

    <x-pageTitle parentTitle="Politikalar" parentRoute="{{ route('policy.index') }}" title="Yasaklı Ürünler" />

    <section class="clearfix">
        <div class="sbst-service-area pd-top-112">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-xl-12 col-lg-10">
                        <div class="section-title ">

                            <p><strong>Satıcılar, aşağıda sayılan ve Şirket tarafından her zaman tek taraflı olarak değiştirilebilecek ürünleri satışa sunmayacaklarını, belirtilen ürünleri satışa sunduklarının tespiti halinde Şirket’in üyeliği sonlandırma da dahil olmak ve fakat bununla sınırlı olmamak üzere her türlü önlemi alabileceğini peşinen kabul, beyan ve taahhüt ederler.</strong></p>

                            <p><strong>- Ürün Vasfını Haiz Olmayan Listelemeler:</strong> Exxefy’da yapılan tüm listeleme içeriklerinin ürün vasfını taşıması şarttır. Ürün vasfını taşımayan, mal veya hizmet kapsamına girmeyen tüm içeriklerin satışı ve tanıtımı yasaktır. Bu kapsamda, Satıcılar tarafından listelenen ürünlerin niteliği, kapsamı, adedi, ürünle ilgili Alıcıların bilmesi gereken tüm bilgiler listeleme içeriğine alınmalıdır. Satıcıların listeledikleri mal ve hizmetleri, listeledikleri şekilde satmaları esastır. Bu kapsamda, listelenen ürünü paravan olarak kullanıp, kasıtlı olarak bu ürün dışında farklı bir ürünün satışa sunulması yasaktır. Bu konudaki sorumluluk yalnızca ve sadece Satıcı üzerindedir.</p>
                            <p><strong>- Mali Hizmetler:</strong> Bitcoin, Etherium, Ripple vb. sanal ve/veya kripto paraların doğrudan veya dolaylı satışı ve veri ve de sanal para madenciliği ile sistemler, ürünler ve hizmetlerin satışa sunulması yasaktır. Her türlü piramit satış modelleri ve/veya saadet zincirlerine ilişkin satışlar; üçüncü kişilere kredi tahsisi veya tahsis taahhüdüne ilişkin satışlar, her tür yatırım işlemleriyle ilgili satışlar; hisse senedi, tahvil, bono veya sair yürürlükte olan, borsada işlem gören değerli evrakların satışı ile bankacılık faaliyeti yürütmeye yetkili kuruluşlar haricindeki kişilerce yapılan faizle para satışı ve benzeri faaliyetlerin tanıtımı; dernek, kulüp, vakıf veya sair tüzel kişiliği haiz olsun olmasın topluluk ve/veya ticari işletmeler için kitle fonlama çağrısında bulunma ve/veya bağış veya aidat toplama; fatura ödemeye ilişkin işlemlerin tamamı ve tahsilata konu edilebilecek her türden mal ve hizmet satışı yasaktır.</p>
                            <p><strong>- Telekomünikasyon Hizmetleri:</strong> Dakika paketi, SMS, internet paketi ve benzeri, kontör, dakika, kısmi veya bütün paket satışları da dahil olmak ve fakat bunlarla sınırlı olmamak üzere telekomünikasyon hizmeti olarak tanımlanabilecek her türlü ürün ve hizmetin satışı yasaktır.</p>
                            <p><strong>- Sağlık Beyanlı (Endikasyon Bilgisi İçeren) Ürünler:</strong> Sağlık Bakanlığı’nın 25.04.2014 tarihli Bilgilendirme Yazısı uyarınca, tanıtımında sağlık beyanı yani “ insan sağlığına doğrudan veya dolaylı olarak faydalı olduğu yahut hastalıklara veya belirtilerine karşı etkili olduğu, koruduğu, tedavi ettiğini belirten, ileri süren veya ima eden ifadeler ” içeren ürünlerin tanıtım ve satışı yasaktır.</p>
                            <p><strong>- Reçeteli veya Reçetesiz Satılan İlaçlar, Lensler, Numaralı Gözlükler:</strong> Evcil hayvanlara verilenler de dahil olmak üzere doktor reçetesiyle verilen her türlü ilaç, reçeteli veya reçetesiz ilaç yapımında kullanılan her neviden maddelerin, ilaç özelliği olmasa dahi sağlık kategorisinde bulunan tüketim ürünlerinin (gıda takviyesi, vitamin, vb.), doktor reçetesiyle alınabilen numaralı gözlükler, numaralı gözlük camı, lensler; işitme cihazlarının tanıtım ve satışı yasaktır.</p>
                            <p><strong>- Ateşli Silahlar, Bıçaklar, Askeri Teçhizat, Yanıcı ve Patlayıcı Maddeler:</strong> Kurusıkı, havalı, pompalı, fişek atan, gerçek mermi veya plastik mermi atan, çalışan veya çalışmayan tüm ateşli silahların, biber gazı (göz yaşartıcı gaz), elektro şok cihazlarının, her türlü askeri mühimmatın (mermi, el bombası, molotof kokteyli, kara-deniz mayınları vb.), patlayıcı maddelerin, saldırı ve savunmada kullanılmak üzere imal edilmiş her türlü ateşli silahların; koleksiyon özellikleri bulunan ve en az 50 (elli) yıl evvel üretilmiş olanlar ile eskrim sporunda kullanılan kılıçlar ve mutfak gereci olarak yiyecek maddelerini hazırlamada kullanılan kesme ve doğrama bıçakları hariç olmak üzere her türlü kesici ve delici aletin (sustalı bıçak, kasatura, pala, topuz, kılıç, muşta, kama vb.); silah yapımına ilişkin her türlü malzemenin ve gübre de dahil olmak ve fakat bununla sınırlı olmamak üzere hammaddenin, tarif, kroki, çizim, 3D çizim ve benzeri bilgi satış kaynaklarının; şenlik ve işaret fişekleriyle oyun ve eğlence aracı olan patlayıcı maddelerin brüt beş kilogramı aşan miktarlardaki satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Kültür ve Tabiat Varlıkları, Madalya ve Nişanlar:</strong> 2863 sayılı Kültür ve Tabiat Varlıkları Kanunu’nda belirtilen " Millî tarihimizdeki önemleri sebebiyle, Millî Mücadele ve Türkiye Cumhuriyetinin kuruluşuna ait tarihî değer taşıyan belge ve eşyalar, Mustafa Kemal Atatürk’e ait zatî eşya, evrak, kitap, yazı ve benzeri taşınırlar " hükmü kapsamında korunması gerekli taşınır kültür ve tabiat varlıkları korunmasının gerekli olup olmadığının tespiti açısından "Korunması Gerekli Taşınır Kültür Ve Tabiat Varlıklarının Tasnifi, Tescili Ve Müzelere Alınmaları Hakkında Yönetmelik” hükümleri doğrultusunda tasnif ve tescile tabi tutulmaktadır. Tasnif ve tescil dışı bırakılan ve müzelere alınması gerekli görülmeyen eserler sahiplerine bir belge ile iade edilir. Tasnif ve tescile ilişkin belgesi olmayan eserlerin Exxefy üzerinden satışı ve tanıtımı yasaktır. 2933 Madalya ve Nişanlar Kanunu uyarınca; Devlet Şeref Madalyası, Devlet Övünç Madalyası, Devlet Üstün Hizmet Madalyası, Devlet Savaş Madalyası ve Devlet Nişanı, Cumhuriyet Nişanı, Liyakat Nişanıları’nın Exxefy üzerinden satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Tütün ve Mamülleri ile Elektronik Sigara:</strong> 4207 sayılı Tütün Ürünlerinin Zararlarının Önlenmesi Ve Kontrolü Hakkında Kanun’un 3. maddesinin 1., 2., 5., 11. ve 14. fıkraları uyarınca, tütün, tütün mamülleri ve benzeri ürünler ile bu ürünlere ait isim, marka ya da ibare taşıyan ya da bu ürünlere benzeyen ya da bunları çağrıştıran şekillerde olan her türden ürünler; sigaralar, purolar ve elektronik sigaralar ile elektronik sigara kartuşlarının satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Alkollü İçecekler:</strong> Her türlü alkollü içkinin satışı ve alkollü içkilere ilişkin reklam, tanıtım, promosyon yapılması yasaktır.</p>
                            <p><strong>- Uyuşturucu ya da Bağımlılık Yaratan Maddeler ile Bunların Kullanımını Sağlayan Araçlar:</strong> Yasal olmayan, yürürlükteki mevzuat uyarınca satılması ve tüketilmesi yasak olan doğal ya da kimyasal maddeler ile her türlü uyuşturucu ve uyarıcı maddelerin satışı ve bunlarla ilgili herhangi bir paylaşımda bulunmak yasaktır.</p>
                            <p><strong>- Organ Satışı:</strong> İnsanların, insan organlarının ve vücut parçaları ile kan, kemik, sperm ve benzeri maddelerin satışı yasaktır.</p>
                            <p><strong>- Hayvan Satışı:</strong> Evcil hayvanlar da dahil olmak ve fakat bununla sınırlı olmamak üzere her türden hayvan satışı yasaktır.</p>
                            <p><strong>- Trafik Aygıtları:</strong> Radar dedektörleri, radar kilitleyiciler, araç plakası örtüleri, trafik işareti değiştiriciler ve ilişkili ürünlerin satışı yasaktır.</p>
                            <p><strong>- Telsiz ve Telekomünikasyon Cihazları:</strong> Kısa Mesafe Erişimli Telsiz Cihazları (KET) Yönetmeliği’ne uygun olmayan ve Bilgi Teknoljileri ve İletişim Kurumu’nca verilen lisans gerektiren tüm telsizlerin satışı yasaktır.</p>
                            <p><strong>- Son tüketiciye yönelik elektronik ürünler:</strong> Bilgisayar, cep telefonu, yazıcı, monitör, televizyon gibi kategorilerdeki son tüketicilere yönelik elektronik ve bilişim ürünlerinin satışı yasaktır.</p>
                            <p><strong>- Kopya, Bandrolsüz, Korsan, Taklit Ürünler:</strong> Koleksiyon ve antika değeri taşıyan ürünler hariç olmak üzere, 5846 sayılı Fikir ve Sanat Eserleri Kanunu kapsamda her türlü ses ve görüntü taşıyıcılar ile kitapların bandrolsüz satışı yasaktır. Tasarım, marka veya patent olarak tescil ettirilmiş olan, üçüncü bir kişinin herhangi bir fikri ve/veya sınai mülkiyet hakkını ihlal eden, yasal olmayan yollardan üretilmiş, ticaret hayatına sokulmuş ve/veya ithal edilmiş ürünler, bu ürünlerin kopyaları veya imitasyonları olan ürünlerin satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- IPTV:</strong> İnternet üzerinden televizyon imkanı tanıyan sistemler ve/veya hizmetlerle ilgili içerik satışı yasaktır.</p>
                            <p><strong>- Kişisel Veriler:</strong> Kişilik haklarını ihlal eden her türlü özel haber, fotoğraf, görüntü, telefon numarası, e-posta, ikametgah adresi gibi bilgilerin satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Çöpçatanlık Hizmetleri:</strong> Kişileri birbirleriyle tanıştırma hizmeti de dahil olmak ve fakat bununla sınırlı olmamak üzere, reel veya sanal fark etmeksizin çöpçatanlık hizmetlerinin tamamı; arkadaşlık sitelerinde üyelik açma, kişilerle görüşme ve/veya kişileri görüştürmeye ilişkin hizmetlerin tamamının satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Web Ortamında Saldırma ve Program Kırma Yazılımları:</strong> Web ortamında saldırma ve program kırma (hacking) yazılımları; yazılımlara, sunuculara veya internet sitelerine yasadışı bir şekilde erişmeyi sağlayan yazılımlar; cep telefonlarına ve diğer iletişim veya içerik dağıtım sistemlerine/aygıtlarına yasadışı erişime olanak sağlayan yazılımlar; ücretsiz kablo hizmetleri almak için kablo veya uydu sinyallerini çözen decoder ürünleri; kablosuz internet bağlantılarını yakalayıp şifrelerini kıran yazılım ve ürünler; şifreli yayın yapan yayın kuruluşlarının yayınlarını çözen, her türlü ekran kartı, yazılım, cihaz ve ekipmanların satışı yasaktır.</p>
                            <p><strong>- Yasaklı Yayınlar:</strong> Yürürlükteki mevzuat uyarınca yayını ve dağıtımı suç teşkil eden her türlü bölücü, ırkçı, irticai ve illegal siyasi düşünce ve oluşumları övücü dergi, gazete, kaset, CD, VCD, DVD ve benzeri yayınların satışıve tanıtımı yasaktır.</p>
                            <p><strong>- Sahte Belgeler:</strong> Aslına uygun olmayan ve eğlence amaçlı üretildiği ortalama zekalı kişilerce direkt olarak anlaşılabilenler hariç olmak üzere, sahte kimlikler, pasaportlar, diplomalar, paralar ve asalet ünvanlarının satışı yasaktır.</p>
                            <p><strong>- Şans Oyunları Biletleri, Kuponları, Kağıtları, Kumar:</strong> Sonucu henüz belli olmamış şans oyunlarına ait, bilet, kupon ve benzeri her neviden belgenin satışı yasaktır. At yarışı, maç sonucu tahmine ve benzeri şans oyunu tanımına dahil kabul edilen her türlü satış ile kumar, bahis veya tahmin olarak değerlendirilebilecek tüm satışlar yasaktır.</p>
                            <p><strong>- Cinsel İçerikli ve Pornografik Ürünler, Yetişkinlere Özel Ürün ve Malzemeler:</strong> Her neviden formatta yetişkin cinsel fantezi ürünlerin ve pornografik yayınların (VCD, DVD, VHS, dergi, kitap, broşür vs.); çocuk pornosu veya çocukların uygunsuz görüntülerini ihtiva eden her neviden ürünün; insan genital organlarını cinsel aktiviteye yönelik sunan ürün ve malzemelerin; üzerinde “18+” ibaresi bulunan her neviden ürün ve malzemelerin satışı ve tanıtımı yasaktır.</p>
                            <p><strong>- Yiyecek ve İçecek Maddelerinin Satışı:</strong> Exxefy’da yiyecek ve içecek maddelerinin satışı yasak değildir. Bununla birlikte, satışa sunulan yiyecek ve içecek maddelerinin tazeliğini korur şekilde satışa sunulması ve Alıcılar’ın sağlığını tehdit etmeyecek şekilde Alıcılar’a ulaştırılması yükümlülüğü Satıcılar’ın üzerindedir.</p>
                            <p><strong>- Turizm Hizmetleri, Gezi Hizmeti ve Araç Kiralama Hizmetleri:</strong> Konser, tiyatro veya benzeri etkinlikler dışında gezi hizmetleri veya sair turizm hizmetlerinin satışa sunulması yasaktır. Bunun yanında, her türden araç kiralama hizmetlerinin satışa sunulması da yasaktır.</p>
                            <p><strong>- Drop Shipping:</strong> Exxefy’da imalatçıların ve/veya toptancıların son kullanıcıya doğrudan mal sevk etmesi yasak değildir. Bununla birlikte, Exxefy bu şekildeki satışlara ilişkin olarak Satıcılar’a ek yükümlülükler getirme hakkını saklı tutar.</p>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
