@extends('layouts.web')
@section('title', 'Teslim Koşulları - Exxefy')


@section('content')

    <x-pageTitle parentTitle="Politikalar" parentRoute="{{ route('policy.index') }}" title="Teslim Koşulları" />

    <section class="clearfix">
        <div class="sbst-service-area pd-top-112">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-xl-12 col-lg-10">
                        <div class="section-title ">

                        <p><strong>Exxefy, yalnızca Satıcılar ile Alıcılar’ı kredi kartıyla veya Exxefy’in belirleyeceği diğer ödeme yöntemleriyle ödeme yapılması imkanı sunma maksadı ile bir araya getirmektedir. Satıcılar ve Alıcılar, Şirket’in satışa sunulan Ürünler’in teslimi hususunda, ayrıca açıkça belirtilmediği durumlarda, hiçbir sorumluluğu olmadığını kabul, beyan ve taahhüt ederler.</strong></p>

                            <p>- Exxefy üzerinden Alıcı ve Satıcı’nın bir araya getirilmesi ile kurulan sözleşme kapsamında Satıcı’nın sorumluluğu, Alıcı tarafından satın alınan Ürün’ü mümkün olan en kısa süre içerisinde, tam, eksiksiz, usulüne uygun ve ayıptan ari olarak ve Alıcı’nın Exxefy üzerinden bildirdiği bilgilere uygun olarak göndermek ve Alıcı’nın yükümlülüğü satın aldığı Ürün’ün bedelini Şirket tarafından belirlenen şekilde yatırmak ve kendisine gönderilen Ürün’ü teslim almaktır.</p>
                            <p>- Şirket, İnternet Sitesi üzerinden Ürün satışı yapmamaktadır. Alıcılar tarafından satın alınan Ürünler, Şirket tarafından değil Satıcılar tarafından Alıcılar’ın adreslerine gönderilecektir.</p>
                            <p>- Satıcı, Alıcı’ya karşı Kullanım Koşulları ve Üyelik Sözleşmesi uyarınca Ürün’ü zamanında ve satışa arzında belirttiği niteliklere uygun ve ayıptan arî olarak göndereceğini ve teslimini sağlayacağını; Ürün’ün Alıcı’ya satılması, mülkiyetinin ve ilgili haklarının devrine ilişkin yükümlülüklerin sadece kendisine ait olduğunu kabul eder. Satıcı gönderme ve teslim yükümlülüğünü, Türkiye Cumhuriyeti’nde faaliyet gösteren kargo firmaları aracılığıyla yerine getireceğini, gönderi ile ilgili bilgileri Şirket’in sağladığı satıcı portalı üzerinden gireceğini, bu yükümlülükleri yerine getirmeden gönderi veya teslim yapması halinde Ürün’ün teslim edilememesinden veya benzeri bir durumdan Şirket’in herhangi bir sorumluluğunun doğmayacağını ve Şirket’ten her ne nam altında olursa olsun bir maddi veya manevi talepte bulunmayacağını kabul, beyan ve taahhüt eder.</p>
                            <p>- Satıcı, Alıcı’ya karşı Kullanım Koşulları ve Üyelik Sözleşmesi uyarınca Ürün’ü zamanında ve satışa arzında belirttiği niteliklere uygun ve ayıptan arî olarak göndereceğini ve teslimini sağlayacağını; Ürün’ün Alıcı’ya satılması, mülkiyetinin ve ilgili haklarının devrine ilişkin yükümlülüklerin sadece kendisine ait olduğunu kabul eder. Satıcı gönderme ve teslim yükümlülüğünü, Türkiye Cumhuriyeti’nde faaliyet gösteren kargo firmaları aracılığıyla yerine getireceğini, gönderi ile ilgili bilgileri Şirket’in sağladığı satıcı portalı üzerinden gireceğini, bu yükümlülükleri yerine getirmeden gönderi veya teslim yapması halinde Ürün’ün teslim edilememesinden veya benzeri bir durumdan Şirket’in herhangi bir sorumluluğunun doğmayacağını ve Şirket’ten her ne nam altında olursa olsun bir maddi veya manevi talepte bulunmayacağını kabul, beyan ve taahhüt eder.</p>
                            <p>- Satıcı, Alıcı’ya karşı Kullanım Koşulları ve Üyelik Sözleşmesi uyarınca Ürün’ü zamanında ve satışa arzında belirttiği niteliklere uygun ve ayıptan arî olarak göndereceğini ve teslimini sağlayacağını; Ürün’ün Alıcı’ya satılması, mülkiyetinin ve ilgili haklarının devrine ilişkin yükümlülüklerin sadece kendisine ait olduğunu kabul eder. Satıcı gönderme ve teslim yükümlülüğünü, Türkiye Cumhuriyeti’nde faaliyet gösteren kargo firmaları aracılığıyla yerine getireceğini, gönderi ile ilgili bilgileri Şirket’in sağladığı satıcı portalı üzerinden gireceğini, bu yükümlülükleri yerine getirmeden gönderi veya teslim yapması halinde Ürün’ün teslim edilememesinden veya benzeri bir durumdan Şirket’in herhangi bir sorumluluğunun doğmayacağını ve Şirket’ten her ne nam altında olursa olsun bir maddi veya manevi talepte bulunmayacağını kabul, beyan ve taahhüt eder.</p>
                            <p>- Alıcı’ya sunulacak kargoya ilişkin ücretleri belirlemek ve hangi kargo şirketi ile gönderim yapılacağını belirlemek Satıcılar’ın inisiyatifindedir. Bu sebeple, ödemenin yapılmasından önce Alıcılar’ın Satıcılar’la iletişim kurarak teslim koşulları üzerinde mutabakata varması gerekmektedir. Alıcılar ve Satıcılar, Şirket’in teslime ve/veya Alıcılar’ı ve Satıcılar’ı uzlaştırmaya, buluşturmaya veya anlaştırmaya ilişkin hiçbir sorumluluğu bulunmadığını peşinen kabul etmektedirler.</p>
                            <p>- Taşıma esnasında söz konusu olabilecek zararlar da dahil olmak ve fakat bununla sınırlı olmamak üzere Ürünler’in teslimatına ve yasaklı ürünlere ilişkin olarak Satıcı ve/veya Alıcı tarafından tercih edilen posta hizmet sağlayıcının belirlediği kural ve koşullar geçerlidir. Posta hizmet sağlayıcılarının kural ve koşulları İnternet Sitesi’nde yer alabileceği gibi, gerek Kargo Şirketlerinin ve gerekse diğer posta hizmet sağlayıcının kendi internet sitesinde de bulunabilir. Exxefy’in posta hizmet sağlayıcı şirketlerle anlaştığı fiyatlar üzerinden Satıcılar’ın gönderim yapabilmelerine olanak sağladığı Anlaşmalı Kargo gönderimleri için belirtilen kuralları aşağıda bulabilirsiniz. Şirket’in, Ürünler’in posta hizmet sağlayıcı üçüncü kişi sebebiyle ve/veya vasıtasıyla zarar görmesine ilişkin herhangi bir sorumluluğu bulunmamaktadır. Lütfen Ürünler’i göndermeden önce tercih ettiğiniz posta hizmet sağlayıcının belirlediği kural ve koşulları inceleyiniz.</p>
                            <p>- Satın alınan Ürünler’in teslim edilememesinden Şirket sorumlu değildir. Ürün’ün teslim edilememesi halinde, Şirket’in yegane sorumluluğu, kendisine bu durumun bildirilmesi halinde, durumu Satıcı’ya bildirmektir.</p>
                            <p>- Satıcı, Alıcı’ya satın aldığı Ürün’ün kargo bilgilerini bildirmekle yükümlüdür. Alıcı’ya Ürün’e ilişkin kargo bilgileri, Alıcı’nın Exxefy’de ilgili bölüme girdiği e-posta adresi üzerinden bildirilecektir. Bu sebeple Alıcılar’a ilgili bölüme e-posta adreslerini girmeleri önerilir.</p>
                            <p>- Satıcı, Alıcı’nın Ürün’ün teslimine ilişkin herhangi bir talebi olması durumunda, söz konusu talebi Satıcı Paneli’nde bulunan Müşteri Talepleri bölümünden ve Şirket tarafından kendisine sair şekillerde iletilecek talepleri takip etmek ve çözmekle yükümlüdür.</p>
                            <p>- Exxefy üzerinden verilen Hizmetler’in sağlanabilmesi için Şirket, Satıcı’nın ve Alıcı’nın adı ve soyadı, unvanı, iletişim bilgileri gibi, satın alınan Ürün’ün teslimatının yapılabilmesi için gerekli olan bilgi ve verileri Satıcı’nın gönderim için tercih ettiği posta hizmet sağlayıcı üçüncü kişiler ile paylaşacaktır. Exxefy ile paylaşılan kişisel veriler, 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında işlenmektedir. Kişisel verilere ilişkin daha fazla bilgi edinmek, Satıcı’nın ve Alıcı’nın kişisel verilerinin işlenmesine ve aktarılmasına ilişkin bilgiler için lütfen Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni’ni inceleyiniz.</p>
                            <p>- Ürünlerin gönderilmesinde Alıcı ve/veya Satıcı’dan kaynaklanan her ne nam altında olursa olsun bir usulsüzlüğün söz konusu olması durumunda Exxefy’e, Şirket’e, ortaklarına ve/veya çalışanlarına karşı herhangi bir cezai, adli ve/veya idari yaptırım uygulanması durumunda, Exxefy’in doğmuş veya doğacak her türlü zararının tahsili için ilgili Alıcı ve/veya Satıcı’ya rücu etme hakkı saklıdır.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
