@extends('layouts.web')
@section('title', 'Üyelik Sözleşmesi - Exxefy')


@section('content')

    <x-pageTitle parentTitle="Politikalar" parentRoute="{{ route('policy.index') }}" title="Üyelik Sözleşmesi" />

    <section class="clearfix">
        <div class="sbst-service-area pd-top-112">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-xl-12 col-lg-10">
                        <div class="section-title ">
                            <p><strong>Exxefy'a üye olmanızdan itibaren, aşağıda yazılı olan ve üye olmaya ilişkin önemli bilgiler içeren hususları bütünüyle anlamış ve tamamını ayrılmaz bir bütün olarak kabul etmiş sayılırsınız.</strong></p>

                            <p>Exxefy'a üye olmadan önce lütfen işbu Üyelik Sözleşmesi’ni dikkatle okuyunuz ve Üyelik Sözleşmesi’nin içerdiği tüm maddeleri ve hükümleri onaylamıyorsanız üyelik sürecini tamamlamayınız. Yeni üyelik oluşturma esnasında, bu metni okuduğunuzu ifade eden bir bölümle karşılaşacaksınız, bu kısmı işaretlemeniz aşağıdaki maddelerin tamamını kabul ettiğiniz anlamına gelecektir.</p>

                            <p>Üyelik Sözleşmesi’nde yer almayan her türlü bilgi ve tanım için işbu Üyelik Sözleşmesi’nin Exxefy'daki diğer belge ve açıklamalarla birlikte ayrılmaz parçalarından biri olan Kullanım Koşulları geçerlidir.</p>

                            <p><strong>1. TARAFLAR VE KONU</strong></p>

                            <p><strong>1.1.</strong>&nbsp;İşbu Üyelik Sözleşmesi, Üye veya Satıcı olarak Exxefy'da Ürünler’i satışa sunan kişiler için geçerlidir. Bu nedenle lütfen aşağıda yazılı koşulları dikkatlice okuyunuz. Bu koşulları kabul etmiyorsanız Exxefy'a üye olmayınız</p>

                            <p><strong>1.2.</strong>&nbsp;Exxefy'ın sahibi "Fatih Sultan Mh. Şiir Sk. Relux Plaza No:10 Daire:24 Kat:4 Ümraniye 34771 İstanbul, TÜRKİYE" adresinde yerleşik olan Yunus Emre Öztürk (“Şirket”). Exxefy üzerinden sunulan Hizmetler, Şirket tarafından sağlanmaktadır. Şirket, Exxefy'da yer alan veya alacak olan bilgileri, formları, her neviden içeriği ve işbu Üyelik Sözleşmesi’ni dilediği zaman, ayrıca herhangi bir bildirimde bulunmaksızın değiştirme hakkını saklı tutar.</p>

                            <p><strong>1.3.</strong>&nbsp;Şirket, işbu Üyelik Sözleşmesi’nde belirtilen koşulları her zaman ve herhangi bir ihbarda veya bildirimde bulunmadan değiştirebilir. Bu değişiklikler, İnternet Sitesi’nde Üyelik Sözleşmesi, Üyeler’in tek taraflı beyanı ile değiştirilemez.</p>

                            <p><strong>2. TANIMLAR</strong></p>

                            <p><strong>İNTERNET SİTESİ :</strong>&nbsp;Tüm hakları Şirket’e ait olan www.exxefy.com alan adı ve bu alan adlarına bağlı alt alan adlarından oluşan, Exxefy'ın Satıcılar’ın Ürünler’ini satışa sunabilecekleri, Alıcılar’ın ise bu Ürünler’i görüntüleyebilecekleri platform Hizmetleri’nin sunulduğu internet sitesidir.</p>

                            <p><strong>UYGULAMA :&nbsp;</strong>Tüm hakları Şirket’e ait olan, cep telefonu, tablet ve benzeri taşınabilir cihazlarda çalışan mobil uygulama yazılımdır.</p>

                            <p><strong>UYGULAMA MAĞAZASI :</strong>&nbsp;Tüm hakları Şirket’e ait olan, Exxefy üzerinde kullanılmak üzere oluşturulmuş Uygulamaları ve bu Uygulamalar ile bağlantılı olarak oluşturulan ürün ve hizmetlerin listelenerek sunulduğu mecrayı ifade eder. Uygulamalar ücretiz olarak ya da ücretli sunulabilir. Uygulamaların ücretli olması halinde, ücrete ilişkin detaylar ile her bir uygulamanın kullanım koşulları, kuralları ve benzeri kullanıma ilişkin detayları da Uygulama Mağazası’nda ayrıca belirtilecektir.</p>

                            <p><strong>UYGULAMALAR :</strong>&nbsp;Exxefy üzerinde kullanılmak üzere oluşturulmuş yazılımlardır. Uygulamalar Şirket tarafından oluşturulmuş olabileceği gibi, Uygulama Mağazası’nda satışa ve/veya kullanıma sunulmak üzere üçüncü kişiler tarafından geliştirilmiş de olabilir. Uygulamalara ilişkin olarak Şirket tarafından üstlenilen yükümlülükler ve/veya Uygulama’ya ilişkin koşullar, Uygulama’nın Şirket tarafından veya üçüncü kişiler tarafından geliştirilmiş olmasına göre farklılık arz edebilir. Uygulamalara ilişkin detaylı bilgiler, her bir Uygulama’nın ilgili sayfasında ayrıca belirtilecektir.</p>

                            <p><strong>EXXEFY :</strong>&nbsp;İnternet Sitesi ve Uygulama birlikte “Exxefy” olarak ifade edilmektedir.</p>

                            <p><strong>HİZMETLER :</strong>&nbsp;Exxefy üzerinden Satıcı ve Alıcılar’ın Kullanım Koşulları ve Üyelik Sözleşmesi’nde tanımlı olan işlemleri gerçekleştirmelerini sağlamak amacıyla Exxefy tarafından sunulan platform sağlama Hizmetler’inin tamamını ifade eder. Bu kapsamda Exxefy üzerinden, Satıcılar tarafından Veritabanı’na yüklenen içeriklerin Ziyaretçiler tarafından görüntülenebilmesi, Ziyaretçiler’in Ürünler’e ulaşabilmesi için Ürünler’in listelenmesi ve satılan Ürünler’in raporlanması Hizmetler’i sağlanmaktadır. Şirket, dilediği zaman ve hiçbir bildirimde bulunmaksızın Hizmetler’in tanımını değiştirebilir, Hizmetler’i üçüncü kişilerin kullanımına kapatabilir.</p>

                            <p><strong>ZİYARETÇİ :</strong>&nbsp;Exxefy'a erişen her gerçek ve tüzel kişiyi ifade eder. Ziyaretçi tanımı, Üye, Kullanıcı, Satıcı ve Alıcı tanımlarının tamamını kapsamaktadır.</p>

                            <p><strong>ÜYE :</strong>&nbsp;Exxefy üzerinde, oluşturduğu hesap ile listelediği ürünler ve/veya hizmetler ile içeriklerini kendileri oluşturarak Ürün satışa sunan ve Üyelik Sözleşmesi’nde belirtilen koşullar dâhilinde Exxefy'a üye olmuş gerçek veya tüzel kişileri ifade eder. Üyeler, bundan böyle “Satıcı” olarak da anılabilecektir.</p>

                            <p><strong>KULLANICI :</strong>&nbsp;Exxefy üzerinden satışa sunulan Ürünler’i satın alan her gerçek ve tüzel kişiyi ifade eder. Kullanıcılar bundan böyle “Alıcı” olarak da anılabilecektir.</p>

                            <p><strong>ÖDEME HİZMET SAĞLAYICI:</strong>&nbsp;Şirket’in sözleşmesel ilişki içinde olduğu 6493 sayılı Ödeme ve Menkul Kıymet Mutabakat Sistemleri, Ödeme Hizmetleri ve Elektronik Para Kuruluşları Hakkında Kanun’un 13. maddesine göre 5411 sayılı Kanun kapsamındaki bankalar, elektronik para kuruluşları ve ödeme kuruluşları ödeme hizmeti sağlayıcılarıdır.</p>

                            <p><strong>ÜRÜN :</strong>&nbsp;Exxefy üzerinden Satıcılar tarafından başta Yasaklı Ürünler listesi olmak üzere Kullanım Koşulları, Üyelik Sözleşmesi ve eklerine uygun olarak satışa sunulan ürün ve hizmetleri ifade eder.</p>

                            <p><strong>İÇERİK :</strong>&nbsp;Exxefy üzerinden erişimi mümkün olan, Şirket veya Satıcılar tarafından yüklenmiş olan Ürünler’e ilişkin bilgiler de dahil olmak ve fakat bununla sınırlı olmamak üzere her türlü bilgi, yazı, dosya, resim, video ve benzeri görsel, yazınsal ve işitsel imgelerlerdir. İçerik, bundan böyle “Ürün” olarak da anılabilecektir.</p>

                            <p><strong>HİZMET BEDELİ :</strong>&nbsp;Satıcı tarafından Exxefy'a ödenecek bedeldir.</p>

                            <p><strong>ARAYÜZ :</strong>&nbsp;İçerikler’in Ziyaretçiler tarafından görüntülenebilmesi ve Exxefy Veritabanı’ndan sorgulanabilmesi amacıyla Ziyaretçiler tarafından kullanılan; 5846 sayılı Fikir ve Sanat Eserleri Kanunu (FSEK) kapsamında korunan ve tüm fikri hakları Şirket’e ait olan, Exxefy üzerinden yapılabilecek her türlü işlemin gerçekleştirilmesi için bilgisayar programına komut veren internet sayfalarıdır.</p>

                            <p><strong>VERİTABANI :</strong>&nbsp;İçerikler’in depolandığı, tasnif edildiği, sorgulanabildiği ve erişilebildiği ve mülkiyeti Şirket’e ait olan ve 5846 sayılı Fikir ve Sanat Eserleri Kanunu gereğince korunan veriler bütünü ve bu verilerin okunabilmelerini sağlayan sistemdir.</p>

                            <p><strong>3. GENEL HÜKÜMLER</strong></p>

                            <p><strong>3.1.</strong>&nbsp;İşbu Üyelik Sözleşmesi; Exxefy'ın sahibi olan Şirket ile Hizmetler’den yararlanmak isteyen Üye arasında geçerli olup üyelik için gereken hüküm ve şartları belirlemektedir.</p>

                            <p><strong>3.2.</strong>&nbsp;İşbu Üyelik Sözleşmesi’ni kabul etmekle;</p>

                            <p>§ Gerçek kişi Üyeler 18 yaşından büyük olduklarını ve sözleşme yapmak için gereken fiil ehliyetine sahip olduklarını,</p>

                            <p>§ Tüzel kişi Üyeler ise, Üyelik Sözleşmesi’nin yetkili kişiler tarafından kabul edildiğini ve tüzel kişi için bağlayıcı olduğunu</p>
                                
                            <p>§ Gerçek ve tüzel kişi Üyeler, Exxefy tarafından herhangi bir sebeple üyelikten geçici veya sürekli olarak uzaklaştırılmadıklarını</p>
                                
                            <p>peşinen kabul ve beyan ederler. Ayrıca Üye, Üyelik Sözleşmesi’ni kabul ederek İnternet Sitesi’nde sağlanan Hizmetleri kullanmaya, Exxefy'a giriş yapmaya yetkili olduğunu, Hizmet seçiminde ve kullanımında ve Exxefy'a girişinde her türlü sorumluluğu üstlendiğini kabul, beyan ve taahhüt eder.</p>

                            <p><strong>3.3.</strong>&nbsp;Üye kabulünde takdir yetkisi yalnızca ve sadece Şirket’e aittir. Üyelik başvurusu Şirket tarafından değerlendirilecek olup Şirket herhangi bir gerekçe göstermeye gerek duymadan üyelik taleplerini geri çevirme hakkına sahiptir. Şirket kullanılmayan üyelikleri geçersiz kılma hakkını haizdir. Üyelik işlemleri tamamlandıktan sonra da, Şirket, üyeliği geçici olarak veya sürekli olarak durdurmak, iptal etmek, ayrıca hiçbir neden göstermeksizin Hizmet vermeyi kesmek hakkını haizdir.</p>

                            <p><strong>3.4.</strong>&nbsp;Üyelik Exxefy'ın ilgili bölümünden Üye olmak isteyen Ziyaretçiler tarafından İnternet Sitesi’ne üye olmak için gerekli olan üyelik formunun doldurulması, kimlik bilgilerinin verilmesi, gerek görülmesi halinde kimlik bilgilerinin doğruluğunun onaylanması, üyelik formunda verilen bilgilere göre yararlanılmak istenilen hizmetler arasında ücretli bir hizmetin varlığı halinde bu hizmete ilişkin olarak varsa öncül ücretin ödenmesi ve banka bilgileri ve benzeri ödeme ve hesap bilgilerinin verilmesi suretiyle kayıt işleminin yaptırılması ve Şirket’in bu işlemlerin onaylanması ile tamamlanır. Üyeler, banka ve benzeri ödeme ve hesap bilgilerini İnternet Sitesi’nin ilgili bölümlerine girmemeleri halinde Alıcılar’dan tahsilat yapamayacaklarını peşinen kabul, beyan ve taahhüt ederler.</p>

                            <p><strong>3.5.</strong>&nbsp;Hizmetler; (i) Satıcılara, Ürünler’i satışa sunabilecekleri, Alıcılara ise Ürünler’i görüntüleyebilecekleri ve sipariş verebilecekleri bir platform sağlanması ve (ii) Alıcılar tarafından yapılan ödemelerin, ilgili Ürün’ün Alıcı tarafından teslim alınmasını takiben Satıcı’ya aktarılmasının sağlanmasıdır. Bu noktada Exxefy'ın, Satıcılar tarafından kargoya teslim edilen Ürünler’in içeriği kontrol etme yükümlülüğü bulunmamaktadır. Bu kapsamda, Satıcı’nın ilgili Ürün’ü Alıcı’ya göndermemesi halinde veya Alıcı tarafından kendisine gönderilen Ürün’ün vaat edilenden farklı, ayıplı, noksan çıkması halinde Alıcı tarafından gönderilen bedel Alıcı’ya iade edilir.</p>

                            <p><strong>3.6.</strong>&nbsp;Exxefy ve bu kapsamda Şirket, 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve 6563 sayılı Elektronik Ticaret Düzenlenmesi Hakkında Kanun kapsamında mesafeli sözleşme kurulmasına aracılık eden ve “Aracı Hizmet Sağlayıcı” sıfatını haizdir.</p>

                            <p><strong>3.7.</strong>&nbsp;Exxefy, Üyeler’in Exxefy üzerinden satışa sundukları Ürünler’in listelenmesi, Alıcılar tarafından Ürünler’in bedelinin ödenmesini takiben verilecek onay dahilinde Alıcılar tarafından ödenen bedellerin ilgili Satıcı’ya aktarılmasını sağlamaktadır. Bu kapsamda Satıcılar, Şirket’in Satıcı namına satışa sunulan Ürünler’in bedelini tahsile yetkili olduğunu kabul ve taahhüt ederler. Alıcılar, Exxefy vasıtası ile ödeme yaparak Satıcılar ile kurdukları sözleşme ilişkisi kapsamındaki ödeme yükümlülüklerini ifa etmiş olurlar. Bu kapsamda Satıcı, Şirket’in Alıcılar tarafından yapılacak ödemelerin ilgili Ürün’ün Alıcı tarafından teslim alınmasını takiben Satıcı’nın hesabına aktarılması hususunda yetkili olduğunu ve de Hizmetler karşılığında hizmet bedeli ödemekle yükümlü olacağını, peşinen kabul ve taahhüt eder.</p>

                            <p><strong>3.8.</strong>&nbsp;Üyeler, Alıcılar’dan tahsilat yapabilmek için Hizmet Bedeli Koşulları’nın geçerli olduğunu peşinen kabul eder.</p>

                            <p><strong>3.9.</strong>&nbsp;Üyeler, Kullanıcılar ve Ziyaretçiler, Şirket’in, Exxefy'ın ilgili bölümlerine girilen hiçbir bilgiyi kontrol etmekle yükümlü olmadığını ve kendisine verilen bilgilerin doğruluğunu hiçbir koşul altında taahhüt etmediğini peşinen kabul, beyan ve taahhüt eder. Bununla birlikte Ziyaretçiler, Hizmetler’in talep edilen şekilde verilebilmesi için Exxefy'a kendilerine ait, gerçek ve eksiksiz bilgileri vermekle yükümlü olduklarını; aksi takdirde, satın aldıkları Ürünler’in verdikleri adrese ulaşması da dahil olmak, ancak bununla sınırlı olmamak üzere çeşitli sorunların doğabileceğini kabul ederler. Bu kapsamda, Ziyaretçiler Exxefy üzerinden kendilerinden talep edilen bilgileri tam, doğru ve gerçeğe uygun şekilde vermekle yükümlü olup söz konusu bilgileri yanlış vermelerinden dolayı Şirket’in her türlü zararını karşılamakla yükümlüdür.</p>

                            <p><strong>3.10.</strong>&nbsp;Üye, kendisine ait kullanıcı adı ve şifre bilgilerini korumakla yükümlüdür. Üye, kendisine ait bu bilgileri üçüncü şahıslara açıklayamaz ve üçüncü şahısların kullanımına sunamaz. Üye, kendisine ait bu bilgilerin izinsiz kullanıldığını öğrenirse durumu derhal Exxefy'a bildirmeyi taahhüt eder. Şirket, izinsiz kullanımı engellemek amacıyla Üye’nin Exxefy'a erişimini engelleme ve/veya üyeliğini sona erdirme hakkına sahiptir.</p>

                            <p><strong>3.11.</strong>&nbsp;Exxefy, Veritabanı’nda tutulan bilgileri, istatistiki bilgilere dönüştürmek, reklam ve/veya pazarlama alanında kullanmak, Ziyaretçiler’in genel eğilimlerini belirlemek, içeriğini ve servislerini bu anlamda Ziyaretçiler’e daha zengin içerik sunabilmek amacıyla geliştirmek için kullanabilme hakkına her zaman sahiptir.</p>

                            <p><strong>3.12.</strong>&nbsp;Exxefy, Üyeler tarafından gönderilen Ürün bilgileri ve/veya yorum ve öneriler ile bu ürün bilgileri, yorum ve önerilere ilişkin varsa fotoğraflar da dahil olmak üzere her türlü İçerik’i, internet ortamında da dahil olmak üzere her türlü tanıtım materyalinde her şekilde kullanabilir.</p>

                            <p><strong>3.13.</strong>&nbsp;Exxefy ile paylaşılan kişisel veriler, 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında işlenmektedir. Kişisel verilere ilişkin daha fazla bilgi edinmek için lütfen Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni’ni inceleyiniz.</p>

                            <p><strong>3.14.</strong>&nbsp;18 yaşından küçük kişiler Exxefy'a Üye olamazlar ve Ürün satışa sunamazlar. Üyeler’in 18 yaşından küçük olduğunu tespiti halinde üyelik işbu Üyelik Sözleşmesi hükümlerine aykırılık sebebiyle derhal ve ayrıca herhangi bir bildirimde yapılma zorunluluğu olmaksızın sona erdirilir.</p>

                            <p><strong>3.15.</strong>&nbsp;Yarışmalar, promosyonlar ve diğer benzer özellikler dâhil olmak üzere Ürün satışına ve alımına ve Exxefy'ın belli kısımlarının veya özelliklerine ilişkin ek kurallar uygulanabilir ve söz konusu kuralların tamamı, bu referansla işbu Üyelik Sözleşmesi’nin eki ve ayrılmaz bir parçası haline gelir. Üyeler, İnternet Sitesi’nde sunulan Hizmetler’i kullanmak için yeterli yasal yaşta olduklarının beyanı da dâhil olmak üzere, söz konusu kuralların tamamına uymayı kabul ederler.</p>

                            <p><strong>3.16.</strong>&nbsp;Şirket, satın alma miktarlarını sınırlama hakkını saklı tutar.</p>

                            <p><strong>3.17.</strong>&nbsp;Şirket, Ürün görsellerini orijinal renklerine mümkün olan en yakın şekilde göstermek için çaba sarf eder, ancak Ürünler’in renklerinin doğruluğu noktasında hiçbir şekilde taahhütte bulunmamaktadır.</p>

                            <p><strong>3.18.</strong>&nbsp;Şirket, Hizmetler kapsamında hiçbir Üye’ye belirli bir amaca uygunluk, kesintisiz devamlılık, güncelleme, satış garantisi, işlevsellik, doğruluk, hatasızlık dahil, açık ya da zımni hiçbir garanti vermez. Şirket, gerekli gördüğü zamanlarda hizmetleri geçici bir süre askıya alabilir veya tamamen durdurabilir. Hizmetler’in geçici bir süre askıya alınması veya tamamen durdurulmasından dolayı Şirket’in Üyeler’e karşı herhangi bir sorumluluğu yoktur.</p>

                            <p><strong>3.19.</strong>&nbsp;Şirket, Üyeler’e uyguladığı Hizmet Bedeli’nde her zaman ve Üyeler’e ayrıca bir bildirimde bulunmaksızın tek taraflı olarak değişiklik yapabilir. Hizmet Bedeli’ne ilişkin değişiklikler, değişikliğin ilan edildiği andan itibaren geçerlilik kazanacak ve herhangi bir kampanyanın bulunması halinde, kampanyanın sona erme tarihine kadar geçerli olacaktır.</p>

                            <p><strong>3.20.</strong>&nbsp;Şirket, Alıcılar’dan Satıcılar adına tahsil edilecek ödemeler dışında, hiçbir koşul altında Alıcılar’ı ve/veya Satıcılar’ı temsil etmemektedir. Şirket’in Satıcı ve Alıcı arasında ortaya çıkabilecek herhangi bir uyuşmazlık ve benzeri durumda Satıcı ve Alıcı arasındaki iletişimi sağlamak da dahil olmak üzere herhangi bir yükümlülüğü olmadığı gibi, Satıcı ve Alıcı arasında herhangi bir uyuşmazlık çıkması halinde Şirket, söz konusu uyuşmazlığa ilişkin taraf olarak gösterilemez.</p>

                            <p><strong>4. ÜYELER’İN HAK VE YÜKÜMLÜLÜKLERİ</strong></p>

                            <p><strong>4.1.</strong>&nbsp;Üye, Exxefy'da yayınlanan kurallara uygun olarak Hizmetler’den faydalanmayı kabul ve taahhüt etmiştir. Şirket, dilediği zaman duyuru ve/veya bildirim yapmak suretiyle, kullanım koşul ve kurallarında değişiklik yapma hakkını haizdir. Herhangi bir değişiklik halinde Üyeler kazanılmış ve/veya önceye dayalı hak iddiasına bulunamazlar. Bu kapsamda, Exxefy üzerinde yayınlanan kurallar ve duyurular da işbu Üyelik Sözleşmesi’nin eki ve ayrılmaz bir parçasıdır.</p>

                            <p><strong>4.2.</strong>&nbsp;Üyeler, Exxefy üzerinde yalnızca hukuka uygun işlemler yapabilirler. Üyeler’in, Exxefy'da yaptığı her işlem ve eylemdeki hukuki ve cezai sorumluluk bizzat ve sadece kendilerine aittir. Bu kapsamda Üyeler, yapacakları tüm işlemde yürürlükteki mevzuata riayet edeceklerini ve mevzuatın düzenlemiş olduğu tüm sorumlulukların kendilerine ait olduğunu kabul ve beyan eder.</p>

                            <p><strong>4.3.</strong>&nbsp;Üyeler, yürürlükte olan mevzuatın yüklediği sorumlulukları bilmedikleri veya bilebilecek durumda olmadıklarını ileri süremez. Exxefy, mevzuata aykırı olduğunu veya herhangi bir konuda karışıklığa sebep olacağını tespit ettiği İçerikler’i yayımlamaktan imtina edebilir. Şirket’in, yayımlanan veya yayımlanmamasına rağmen Exxefy'ın bulunduğu bilişim sistemlerine Üye tarafından herhangi bir şekilde girilen herhangi bir bilgi veya veri sebebi ile bir hukuki veya cezai sorumlulukla karşılaşması halinde Üye’ye rücu hakkı saklıdır.</p>

                            <p><strong>4.4.</strong>&nbsp;Üye, Alıcı tarafından bedeli ödenerek satın alınan Ürün’ü, mücbir sebep halleri dışında olmak üzere, her ne sebeple olursa olsun Alıcı’ya göndermekten imtina edemez. Böyle bir durumda Şirket’in herhangi bir hukuki veya cezai sorumluluğu bulunmamakla birlikte, Alıcı tarafından durumun ihbarı halinde Şirket, Üye’nin üyeliğini geçici ya da sürekli olarak dondurabilir, üyeliğini sonlandırabilir. Bu takdirde Üye, Şirket’in herhangi bir zararı olması halinde tüm zararını karşılamakla yükümlü olacağını peşinen kabul ve taahhüt eder.</p>

                            <p><strong>4.5.</strong>&nbsp;Ürün’e ait kargo bilgileri ve teslimatın takibine ilişkin uyarı, Alıcılar’ın verdikleri e-posta adresine Exxefy tarafından bildirilecektir. Alıcılar’ın e-posta adreslerini hiç, tam veya gerçeğe uygun şekilde girmemeleri halinde Exxefy'ın Alıcılar’a bildirimde bulunma yükümlülüğü yoktur. Exxefy ve Şirket, Ürün’ün kargo marifeti ile Alıcı’ya teslimine ilişkin hiçbir sorumluluk üstlenmez. Ürün’ün kargo ile gönderilmesi ve teslimatından yalnızca ve sadece Üye sorumludur.</p>

                            <p><strong>4.6.</strong>&nbsp;Ürün’ün teslimatından sonra Alıcı’nın yaptığı ödemenin ilgili banka veya finans kuruluşu tarafından herhangi bir sebeple ödenmemesi, iptali veya Şirket hesaplarından geri çekilmesi hallerinde Satıcı’nın Ürün’ü gönderme yükümlülüğü doğmaz. Satıcı’nın Ürün’ü göndermesinden ve Ürün’ün tesliminden sonra ödemenin gerçekleşmediğinin anlaşılması halinde Alıcı teslim aldığı Ürün’ü Satıcı’ya göndermekle yükümlüdür. Bu takdirde Alıcı, en geç 24 saat içerisinde Ürün’ü Satıcı’nın belirteceği adrese göndermekle yükümlüdür. Alıcı ve Satıcı, Exxefy'ın ve Şirket’in bu konuda herhangi bir yükümlülüğü bulunmadığını, bu sebeple Exxefy'dan ve Şirket’ten herhangi bir talepte bulunmayacaklarını kabul, beyan ve taahhüt ederler.</p>

                            <p><strong>4.7.</strong>&nbsp;Tüm Üyeler, Exxefy'da tanımlı olan bilgilerinin (isim, soy isim, telefon, TC kimlik numarası, adres, e-posta, banka hesap bilgisi) doğru ve kendilerine ait olduğunu kabul ve beyan eder. Exxefy bu bilgilerin doğru olmadığını tespit eder ise, Üye’ye ayrıca herhangi bir bildirimde bulunmaksızın, işlemi, satışı, üyeliği iptal edebilir ya da uygun gördüğü diğer yaptırımları uygulayabilir.</p>

                            <p><strong>4.8.</strong>&nbsp;Exxefy ve Şirket, dilediği zaman Üye’nin üyeliğini sebep göstermeksizin ve ihbarda bulunmaksızın geçici veya sürekli olarak askıya alabilir, belirlenecek sair sınırlamalara tâbi tutabilir veyahut da işbu Üyelik Sözleşmesi’ni tek taraflı olarak feshedebilir. Üyelik feshedilmesi veya askıya alınması durumunda Üyenin Şirket’ten mevcut bir alacağının olması halinde, Şirket bunu muhtemel bir zarardan mahsup etmek amacı ile alıkoyabilir.</p>

                            <p><strong>4.9.</strong>&nbsp;Alıcı’nın hatalı, yetkisiz veya şüpheli bir işlem sebebiyle Ürün’ü iade etmesi ve geri ödeme talep etmesi halinde ve Şirket’in, iş ortağı olan üçüncü kişilerin ve/veya Ödeme Hizmet Sağlayıcı’nın Alıcı’ya herhangi bir şekilde geri ödeme veya zarar tazmininde bulunması veya ilgili idari kurumlar nezdinde idari yaptırıma tabi olması halinde Şirket’in, iş ortağının ve/veya Ödeme Hizmet Sağlayıcı’nın uğrayacağı tüm zarar ve ziyan için Satıcı’ya rücu edilecek ve bu durumda Satıcı tarafından Şirket’in ilk talebini takiben tüm zarar ve ziyan tüm ferileri ile birlikte ödenecektir. Şirket’in böyle bir durumda, Satıcı tarafından ödenmesi gereken bedelleri Satıcı’ya yapılacak ödemelerden mahsup hakkı saklıdır. Satıcı, bu durumlarda Şirket’ten Hizmet Bedeli iadesi talep edemez.</p>

                            <p><strong>4.10.</strong>&nbsp;Üyelik Sözleşmesi, Kullanım Koşulları ve eklerine aykırılık hallerinde Şirket’in maddi ve manevi zararının tazminini talep hakkı saklıdır. Üyelik Sözleşmesi, Kullanım Koşulları ve ekleri Exxefy'ın herhangi bir sebeple yayınının durması/durdurulması halinde bu süre boyunca askıda sayılır. Bu süreçte askıda kalan satış işlemleri için Üyeler ve Kullanıcılar bir tazmin talebinde bulunamaz.</p>

                            <p><strong>4.11.</strong>&nbsp;Üyelik Sözleşmesi, Hizmetler’in sona erdirilmesi halinde kendiliğinden sona erer. Şu kadar ki, Şirket işini, ticari ortaklığını ve alan adını da değiştirmeye, aynı faaliyeti başka bir alan adı üzerinden yürütmeye yetkili olup bu değişikliklerin Üyelik Sözleşmesi’ne herhangi bir etkisi olmayacaktır.</p>

                            <p><strong>4.12.</strong>&nbsp;Üyeler tarafından Ürünler üzerinde yapılacak değişiklikler Exxefy'ın sorumluluğunda değildir. Bu değişiklikler sebebiyle doğabilecek her türlü fikri ve sınai mülkiyet ihlallerinden, bu ihlallerden dolayı üçüncü kişilerin uğrayabileceği her türlü zarardan ve doğabilecek hukuki ve cezai tüm sorumluluklardan ilgili Üye tek başına sorumludur.</p>

                            <p><strong>4.13.</strong>&nbsp;Üye, Ürün’ü satışa sunarken, teslimatta ve satış sonrasında Kullanım Koşulları, Üyelik Sözleşmesi ve ekleriyle birlikte yürürlükte bulunan tüm mevzuata uygun davranmayı, aksi halde karşılaşacağı tüm hukuki ve cezai yaptırımlardan, maddi ve manevi tazminat taleplerinden kendisinin sorumlu olacağını, Şirket’i hiçbir şekil ve surette sorumlu tutmayacağını ve Şirket’in üçüncü kişilerin taleplerine maruz kalması halinde kendisine rücu edebileceğini kabul, beyan ve taahhüt eder.</p>

                            <p><strong>4.14.</strong>&nbsp;Üye, Exxefy'da yaptığı her türlü iş ve işlemin sorumluluğunun kendisine ait olduğunu; burada gerçekleştirilen iş ve işlemleri kendisinin gerçekleştirmediği yolunda herhangi bir def’i ve/veya itiraz ileri süremeyeceğini ve/veya bu def’i veya itiraza dayanarak yükümlülüklerini yerine getirmekten kaçınmayacağını kabul, beyan ve taahhüt eder.</p>

                            <p><strong>4.15.</strong>&nbsp;Şirket, gerekli gördüğü durumlarda Üye’ye önceden uyarıda bulunma gerekliliği olmadan (özellikle, ancak sınırlı olmamak üzere, çalıntı, orijinal olmayan, kaçak ve/veya sahte ürün satışlarında) Üye hakkında gerekli yasal işlemin yapılması amacıyla Cumhuriyet Savcılıklarına ve ilgili denetleme ve düzenleme kuruluşlarına Üye’yi şikayet veya ihbarda bulunabilir. Üye, yasaklı ya da hukuka aykırı Ürün’ün satışıyla bağlantılı olarak Şirket’in şikayeti ve/veya bilgi temini sonucu zarara uğraması durumunda, Şirket’i hiçbir sıfatla sorumlu tutmamayı, Şirket’ten tazminat talep etmemeyi kabul ve taahhüt eder.</p>

                            <p><strong>4.16.</strong>&nbsp;Üyeler, yaptıkları satışa ilişkin KDV faturası keserek Alıcı’ya göndermekle yükümlüdür. Şirket yalnızca, Üyelere verdiği hizmet karşılığında elde ettiği gelire ilişkin olarak fatura kesmekte olup bu faturalara üyelik panelleri içinden ulaşılabilmektedir.</p>

                            <p><strong>4.17.</strong>&nbsp;Üyeler’in Uygulama Mağazası’ndan yapacakları her türlü işlem bakımından Uygulama Mağazası Kullanım Koşulları geçerlidir.</p>
                        
                            <p><strong>5. ÜYELİK PROFİLLERİ</strong></p>

                            <p><strong>5.1.</strong>&nbsp;Üyeler, Ürünler’i satışa sunmak maksadı ile kendilerine ait bir profil sayfası oluşturmakla yükümlüdür. Bu profil sayfasının oluşturulmasında Üyeler, kendilerinden talep edilen kendilerine ait bilgileri (isim, soy isim, telefon, TC kimlik numarası, adres, e-posta, banka hesap bilgisi vs.) ilgili yerlere gireceklerdir. Üyeler tarafından verilen bilgilerden bazıları Hizmetler’de kullanılmak üzere talep edilmekte olup profil sayfasında gözükmeyecektir. Şirket’in profil sayfası da dahil olmak üzere Exxefy'ın her türlü bölümünü dilediği zaman, ayrıca herhangi bir bildirimde bulunmadan değiştirme hakkı her zaman saklıdır.</p>

                            <p><strong>5.2.</strong>&nbsp;Üyeler, profil sayfasında yer alsın almasın, verdikleri bilgilerin doğru ve eksiksiz olduğunu kabul, beyan ve taahhüt eder. Bu bilgilerin eksik verilmesinden kaynaklanan herhangi bir zarardan Exxefy'ın ve/veya Şirket’in sorumlu olması söz konusu olamaz.</p>

                            <p><strong>5.3.</strong>&nbsp;Üyeler, hiçbir gerekçe altında, herhangi bir yöntem kullanarak, kendisine veya diğer Üyeler’e ait profil sayfalarını manipüle edecek davranışlarda bulunamazlar. Üyeler bu gibi davranışlarda bulunmaları halinde Şirket’in tüm zararını tazmin edeceklerini ve Şirket’in tek taraflı olarak ve ayrıca bir ihbarda bulunmadan Üyelik Sözleşmesi’ni feshetme ve Üye’nin üyeliğine son verme hakkı bulunduğunu kabul ederler.</p>

                            <p><strong>5.4.</strong>&nbsp;Üyeler, kendileri için oluşturulmuş profilleri hiçbir şart ve koşulda başka bir kişiye devredemez veya hiçbir şekilde başkalarınca kullanımına izin veremezler. Üyeler’in kendisi için oluşturulmuş profili üçüncü bir kişiye devretmesi veya kullanıma açması halinde Üyeler Şirket’in tek taraflı olarak ve ihbarda bulunmadan Üyelik Sözleşmesi’ni feshetme ve Üye’nin üyeliğine son verme hakkı bulunduğunu kabul ve beyan ederler.</p>

                            <p><strong>5.5.</strong>&nbsp;Her Üye, Exxefy'ı aktif bir e-posta adresi ile kullanmaktadır ve her e-posta adresi yalnızca bir üyelik için kullanılabilir. Üye olan herkes, kullanıcı adı ve şifresini korumakla yükümlüdür. Oluşabilecek kusurlu davranışlardan Exxefy ve/veya Şirket sorumlu değildir. Üyeler, hesaplarında veya şifrelerinde her türlü yetkisiz kullanımı ya da diğer güvenlik ihlallerini derhal Exxefy'a bildirmeyi kabul ederler. Üyeler, hesap bilgilerinin gizliliğini ve güvenliğini sağlayamaması sonucunda başka birinin Üye’nin Exxefy profilini, şifre veya hesabını kullanması nedeniyle Şirket’in ve/veya Ziyaretçiler’in uğrayacağı zararlardan sorumludur.</p>

                            <p><strong>5.6.</strong>&nbsp;Üyeler, profillerinde yayınlanan Ürün fotoğrafları ya da profil fotoğraflarının kendilerine ait olduğunu, gerçeği yansıttığını ve toplumsal ahlak kurallarına uygun olduğunu peşinen kabul, beyan ve taahhüt eder. Bu hükme aykırılık olması halinde Şirket ayrıca bir ihbarda bulunmaksızın ilgili Üye’nin üyeliğini iptal edecektir.</p>

                            <p><strong>6. ÜRÜN SATIŞINA İLİŞKİN KURALLAR</strong></p>

                            <p><strong>6.1.</strong>&nbsp;Üyeler, Exxefy dışındaki platformlardan satışa sundukları Ürünler’i Alıcılar’a kredi kartı ve/veya Şirket’in belirleyeceği diğer ödeme yöntemleri ile satın alma imkanını sağlamak maksadı ile Exxefy'da söz konusu Ürün’e ilişkin bilgileri içeren bir sayfa oluşturacak ve bu sayfaya ilişkin URL’yi Exxefy dışındaki platformlarda paylaşacaklardır. Üyeler, söz konusu URL’nin Exxefy dışındaki platformlarda paylaşılmaması halinde Alıcılar’ın Exxefy üzerinde söz konusu Ürün’e erişme imkanı bulamamasına sebep olabileceğini peşinen kabul eder. Bu sebeple Üyeler’in Exxefy'da oluşturdukları sayfalara ilişkin URL’yi diğer platformlarda da paylaşması esastır.</p>

                            <p><strong>6.2.</strong>&nbsp;Üyeler, belirlenen bölümlerde ve kurallara uygun olarak Exxefy'da Ürün satışa sunabilirler. Üyeler, bu Hizmet için herhangi bir ücret talep edilmesi halinde Ürün’ü Exxefy'da satışa sunabilmek için talep edilen ücreti ödemekle yükümlü olacaklarını peşinen kabul ve taahhüt ederler.</p>

                            <p><strong>6.3.</strong>&nbsp;Üye, Exxefy'a tüketicinin korunması, fikri haklar, haksız rekabet, reklam ve gümrük konularını düzenleyenler dahil ancak bunlarla sınırlı olmaksızın herhangi bir mevzuata aykırı İçerik girmeyeceğini ve içeriklerinde mevzuata aykırı beyanların; resim, video gibi görsellerin bulunmayacağını kabul, beyan ve taahhüt eder.</p>

                            <p><strong>6.4.</strong>&nbsp;Üye, İçerikler’de karalama, kötüleme, ticari iftira atma, tehdit veya taciz etme gibi hukuka aykırı fiilleri gerçekleştirmeyeceğini, Exxefy altyapısını herhangi bir şekilde bozacak girişimlerde ve eylemlerde bulunmayacağını, pornografik içerikli metinler ve görseller de dahil olmak üzere Yasaklı Ürünler listesinde bulunan Ürünler’in Exxefy'da yer almasına sağlamayacağını kabul, beyan ve taahhüt eder.</p>

                            <p><strong>6.5.</strong>&nbsp;Satıcı satışa arz ettiği Ürünler üzerinde çekişmesiz bir şekilde mutlak olarak tasarrufta bulunma hak ve yetkisine sahip olduğunu; bahsi geçen ürün ve hizmetlerin kendisi tarafından satılmasına karşı herhangi bir hukuki veya fiili engel bulunmadığını kabul ve taahhüt eder. Satıcı satışa arz ettiği ürün ve hizmetlerin yürürlükteki tüm mevzuata uygun olduğunu kabul ve taahhüt eder. Satıcı satışa arz ettiği ürün ve hizmetlerin tüm hukuki sorumluğunun kendisine ait olduğunu Şirket’in Ürünler’in arzı ve satışı konusunda, hiçbir sıfat altında kendisiyle doğrudan ve dolaylı ilişki içinde olmadığını kabul eder. Üye’nin çekişmesiz olarak üzerinde her türlü hukuki tasarrufta bulunabilme hak ve yetkisine sahip olmadığı Ürünler’in herhangi bir şekilde İçerik olarak Exxefy'a eklenmesi yasaktır. Bu şekildeki içeriklerin Üye tarafından Exxefy'da satışa arz edilmesi, sunulması, tanıtımının yapılması ya da ilanının verilmesi ve bu durumun tespit edilmesi halinde, Exxefy ilgili Ürün’ün arzına ilişkin tüm İçerikler’in yayınını durdurma ve/veya yasaklı ürünü arz eden Üye’nin üyeliğine son verme ve işbu Üyelik Sözleşmesi’ni ayrıca bir ihbara gerek olmaksızın feshetme haklarını saklı tutmaktadır.</p>

                            <p><strong>6.6.</strong>&nbsp;Şirket, Exxefy'da yayınlanan İçerikler’in hukuka aykırı olması, başkalarının şahsi ve ticari haklarına tecavüz niteliği taşıması veya bu yönde yapılan ihtarlara muhatap olması veya Kullanım Koşulları, Üyelik Sözleşmesi ve ekleri ile diğer kural ve koşullara doğrudan veya dolaylı olarak aykırı olması gibi sebeplerle Üye’ye herhangi bir ihtarda bulunmadan ilgili İçerik’in yayınını geçici veya sürekli olarak durdurabilir. Bu takdirde, Şirket’in Üye’ye ilgili İçerik’in yayınlanmasına ilişkin bir ödeme yapılmasının gerekmesi halinde bu ödemeyi yapma yükümlülüğünün ortadan kalkar ve Şirket’e bu konuda yapılan bir ödeme söz konusu ise bu ödeme hiçbir koşul altında iade edilmeyecektir. Bu kapsamda Üye, ödemiş olduğu herhangi bir bedelin iadesini Şirket’ten talep ve dava etmeyeceğini peşinen kabul, beyan ve taahhüt eder.</p>

                            <p><strong>6.7.</strong>&nbsp;Alıcı, Exxefy'da Satıcı’ya ait Ürünler’i Şirket’in sunduğu altyapı ile Exxefy üzerinden yapar. Alıcı’nın satın alma talebi, Ürün’e ilişkin Satıcı tarafından hazırlanan, Exxefy ya da Exxefy dışındaki platformlarda belirtilen koşulları kabul ederek Satıcı ile arasında bir satış akdinin Ürün’ü satın alma talebiyle kurulduğu anlamına gelmektedir. Alıcı bu satın alma talebiyle ilgili Ürün’ü satın almayı kabul ve taahhüt eder.</p>

                            <p><strong>6.8.</strong>&nbsp;Satıcı, Ürün’ü satışa sunarken Listeleme Kuralları’na uygun hareket etmek, listelenen Ürün’ün güncel, yasal ve Yasaklı Ürünler listesine uygun olmasından sorumlu olduğunu ve bu sorumluluğa aykırı davranışlarda bulunmayacağını peşinen kabul ve taahhüt eder.</p>

                            <p><strong>6.9.</strong>&nbsp;Satıcı, Alıcı tarafından ödenen satış bedelinin Hizmet Bedeli’nin kesilmesinden sonra üyelik bilgileri çerçevesinde vermiş olduğu banka hesabına aktarılacağını; bu banka hesabının herhangi bir sebeple bloke olması, banka tarafından kara listeye alınmış olması veyahut da benzeri sebeplerle paranın verilen banka hesabına aktarılamamasından Exxefy'ın hiçbir koşul altında sorumlu olmayacağını; Hizmet Bedeli düşüldükten sonra satış bedelinden kalan miktarı Satıcı’nın Exxefy'a bildirdiği ve sadece Türkiye Cumhuriyeti sınırları içinde olan bir banka hesabına transfer edeceğini; transferden doğan ve bankalar ile diğer üçüncü kişiler tarafından talep edilen herhangi bir masraf var ise bu masrafın da söz konusu satış bedelinden düşülerek Satıcı’ya gönderileceğini; Alıcı ve Satıcı arasında herhangi bir uyuşmazlık çıkması halinde dahi Şirket’in söz konusu Hizmet Bedeli’ni Alıcı veya Satıcı’ya ödemekle yükümlü olmayacağını; bu süreçte Exxefy'ın Alıcı veya Satıcı’nın parası üzerinde Şirket adına hiçbir işlem ve tasarrufta bulunmayacağını kabul ve beyan eder. Bu kapsamda, Hizmet Bedeli’ne ilişkin şartlar, Hizmet Bedeli Koşulları sayfasında belirtilen şekildedir.</p>

                            <p><strong>6.10.</strong>&nbsp;Alıcı tarafından satın alınan Ürün’ün herhangi bir nedenle iade edilmesi halinde Ürün’ün bedelinin Alıcı’ya iade edilmesi sorumluluğu yalnızca ve sadece Satıcı üzerinde olup bu takdirde Şirket, yalnızca Satıcı’dan tahsil ettiği Hizmet Bedeli’ni Alıcı’ya iade edeceğini kabul eder. Bu kapsamda ürün bedelini üstlenme yükümlülüğü her koşul altında Satıcı’nın üzerindedir.</p>

                            <p><strong>6.11.</strong>&nbsp;Exxefy'ın her ne sebeple olursa olsun Alıcı ve Satıcı arasındaki ilişkiyi düzenleme, sağlama, kurma veya sair şekilde oluşturma veyahut da hakemlik yapma yükümlülüğü yoktur. Alıcı ve Satıcı, aralarındaki satış ilişkisinden bizzat ve de şahsen sorumludur ve Exxefy'ın bu konuda herhangi bir sorumluluğu bulunmadığını peşinen kabul ve beyan ederler.</p>

                            <p><strong>6.12.</strong>&nbsp;Satıcı, Ürünler’in üretilmesinin, çoğaltılmasının, satılmasının, dağıtılmasının veya herhangi bir şekilde satışa arzına ilişkin bir fiilde bulunulmasının yürürlükteki herhangi bir düzenlemeye aykırı olmasından dolayı doğabilecek her türlü hukuki, ticari ve idari talebe karşı sorumlu olduğunu, bu yönde Exxefy'a yöneltilen taleplere karşı Şirket’i her türlü adli, ticari ve idari makam önünde savunma yükümlülüğü olduğunu kabul, beyan ve taahhüt eder.</p>

                            <p><strong>6.13.</strong>&nbsp;Satıcı, Ürün’ü zamanında, satışa arzında belirttiği niteliklere uygun ve ayıptan arî olarak göndereceğini ve teslimini sağlayacağını; Ürün’ün Alıcı’ya satışı, mülkiyetinin ve ilgili haklarının devri ile yükümlülüklerin sadece kendisine ait olduğunu kabul eder. Bu kapsamda Satıcı, Exxefy'ın ve Şirket’in Ürün’ün teslimine ilişkin hiçbir yükümlülüğü bulunmadığını, bu yönde taleplerin söz konusu olması halinde Exxefy'ın talepte bulunan Alıcılar’ı kendisine yönlendireceğini peşinen kabul ve taahhüt eder.</p>

                            <p><strong>6.14.</strong>&nbsp;Exxefy; yapılan herhangi bir işleme harcama itirazı bildirimi gelmesi ve/veya ödeme hizmeti sağlayan kuruluşun yapılan işlem aleyhine yapılan itirazı kabul etmesi ve bu kapsamda itirazın kesinleşmesi veyahut da işlemin şüpheli bir işlem olması veyahut da Satıcı’nın işlemleriyle ilgili Exxefy'a Alıcılar’dan birden fazla şikayet ulaşması durumunda; şüpheli işlemlerle ilgili Satıcı’ya Alıcı ve/veya Exxefy tarafından ulaşılamaması, Yasaklı Ürünler Listesi’nde yer alan ürün veya hizmetlerin satışa sunulduğunun tespit edilmesi, söz konusu işlemin Üye’nin genel işlem tutarı ortalamasının üzerinde olması veyahut da işlemin geçerliliği ve hukukiliğine ilişkin herhangi bir nedenle şüphe uyandırması halinde, ilgili işleme ilişkin ödenen ücretin Satıcı’ya aktarılması için Alıcı ve Satıcı’dan ek bilgi ve belgeler talep edebilir. Söz konusu ek bilgi ve belgeler tamamlanıncaya ve/veya Alıcı tarafından yapılan ödeme ilgili işleme ilişkin şüphe ortadan kalkıncaya değin Satıcı’nın hesabına aktarılmayabilir. Bu kapsamda, Alıcı veya Satıcı’dan talep edilen bilgi ve belgelerin Exxefy'a iletilme süresinin dolması durumunda, Alıcı tarafından yapılan ödeme, Exxefy tarafından bloke edilebilir veya ilgili siparişe ilişkin bedelin Alıcı ya da Bankasına iade edilmesi halinde, Exxefy ödediği bedeli Satıcının yapmış olduğu farklı satışlardan mahsup veya tahsil edebilir. Bu hususta karar verme yetkisi yalnızca ve sadece Şirket’e ait olup belirtilen işlem yalnızca Alıcı ve Satıcılar’ın güvenliğini sağlamak maksadıyla kullanılmaktadır.</p>

                            <p><strong>6.15.</strong>&nbsp;Exxefy, Satıcının kargo işlemlerinden doğan herhangi bir borcu bulunması halinde, ilgili borç bakiyesi Exxefy tarafından Alıcının yaptığı ödemeden veya Satıcının farklı siparişlerinden mahsup veya tahsil edilebilir. Bu hususta karar verme yetkisi yalnızca ve sadece Şirket’e aittir.</p>

                            <p><strong>6.16.</strong>&nbsp;Üyeler, her koşulda Şirket’i ve Exxefy'ı kar kaybı da dahil olmak ve fakat bununla sınırlı olmamak üzere herhangi bir zarara uğratmamakla ve Şirket’in ve de Exxefy'ın saygınlığına herhangi bir zarar vermemekle yükümlüdür. Bu kapsamda Satıcılar, Exxefy'da belirtilen tüm koşul ve kurallara uygun davranacaklarını kabul ve taahhüt ederler. Satıcılar, Alıcılar’ın memnuniyetine azami özen göstereceklerini; Alıcılar ile olan ilişkilerini saygı çerçevesinde yürütmekle yükümlü olduklarını ve bu kapsamda Alıcılar’a her ne şekilde olursa olsun hakaretamiz ifadeler kullanmayacaklarını, Alıcılar’ı aşağılayan, karalayan, renciden eden her türlü hareketten kaçınacaklarını; Alıcılar’ın taleplerine ve sorularına en geç aynı gün içinde yapıcı ve memnuniyet odaklı yanıtlar vermekle ve bu kapsamda Exxefy tarafından talep edilmesi halinde Alıcılar ile olan tüm iletişim kayıtlarını Exxefy'a göndermekle yükümlü olduklarını; Exxefy'a verdikleri iletişim bilgilerinin doğru olduğunu ve Exxefy'a kaydettikleri telefon numaralarından mesai saatleri içinde ulaşılabilir olmakla yükümlü oldukları kabul ve taahhüt ederler. İşbu maddede belirtilen yükümlülüğün yerine getirilmemesi halinde Exxefy Satıcı’nın üyeliğini derhal fesih hakkını haiz olmasının yanında, Exxefy'ın Alıcı’ya her ne nam altında ve sebeple olursa olsun, bedel iadesi de dahil olmak ve fakat bununla sınırlı olmamak üzere, bir tazminat ödemesi halinde, ödediği bedeli Satıcı’dan tahsil etme ve/veya Satıcı’nın alacaklarından mahsup etme hakkı saklıdır.</p>

                            <p><strong>7. YASAKLAR VE SORUMLULUK HALİ</strong></p>

                            <p><strong>7.1.</strong>&nbsp;Üyeler, Hizmetler’i hukuka ve yürürlükteki mevzuata uygun bir şekilde kullanmayı kabul ve taahhüt ederler. Üyeler, Hizmetler’i kullanırken yapacakları her işlem ve eylemdeki hukuki ve cezai sorumluluktan bizzat sorumludurlar.</p>
                            
                            <p><strong>7.2.</strong>&nbsp;Üyeler, İçerikler’i çoğaltmayacağını, kopyalamayacağını, dağıtmayacağını, işlemeyeceğini ve gerek bu eylemleri ile gerekse de başka yollarla Exxefy ve/veya Şirket ile doğrudan ve/veya dolaylı olarak sınırlamaları aşan veya ihlal eden İçerikler’i Exxefy'a ekleyen Üyeler’e devlet, yargı makamları veya hak sahibi üçüncü şahıslar tarafından yöneltilen tüm hukuki ve cezai yaptırımlardan bizzat Üye sorumludur. Bu kapsamda, Exxefy'ın ve Şirket’in söz konusu İçerikler’den herhangi bir hukuki veya sözleşmesel sorumluluğu bulunmamaktadır.</p>

                            <p><strong>7.3.</strong>&nbsp;Her ne neviden olursa olsun ve kimden kaynaklanırsa kaynaklansın teknik aksaklıklardan dolayı Exxefy'a ulaşımda meydana gelecek hata ya da kesintilerden Şirket sorumlu tutulamaz.</p>

                            <p><strong>7.4.</strong>&nbsp;Exxefy, çevrimiçi ya da çevrimdışı konumdaki hiçbir Üye’nin davranışlarından sorumlu değildir. Şirket’in, hiçbir koşulda Exxefy'ın kullanımı, Ziyaretçiler arasındaki çevrimiçi veya çevrimdışı her türlü iletişim ve etkileşimden doğan sonuçlardan kayıp, hasar, zarar, ölüm vs. dahi olsa sorumluluğu bulunmamaktadır. Şirket’in herhangi bir sebeple bu tür eylemler neticesinde uğrayabileceği her tür zararın tazminini talep hakkı saklıdır.</p>

                            <p><strong>7.5.</strong>&nbsp;Üyeler suç teşkil edecek, Exxefy'ın kullanımında yasal açıdan takip gerektirecek, yerel ve ulusal yasalara ya da uluslararası anlaşmalara ters düşecek bir durum yaratan ya da böyle durumları teşvik eden, her türlü yasa dışı, hakaret ya da tehdit içeren, küfür içeren, küçük düşürücü, pornografik, rahatsız edici ya da ahlaka aykırı İçerikler yayınlayamaz. Bu konuda Yasaklı Ürünler listesi esastır. Üyeler bir başkasının gizlilik hakkını ya da yayın haklarını çiğneyen, telif hakları, ticari marka hakları veya başka mülkiyet hakları tarafından korunan ya da bu tarif edilen sınıflara giren malzemelerden uyarlanan hiçbir bilgi, yazılım ya da başka bir malzemeyi sahibinden ya da haklarını elinde tutan kişiden izin almaksızın, postalayamaz ya da iletemez. Bu hükmün aykırılığının tespiti halinde Exxefy aykırılığa sebep olan Üye’nin üyeliğini derhal ve ayrıca bir bildirimde bulunmaksızın sona erdirebilir.</p>

                            <p><strong>7.6.</strong>&nbsp;Şirket, Üyeler’e ya da onların e-posta adreslerine, ticari ya da reklam amaçlı istek dışı mesaj gönderilmesi, Üyeler’in bu amaçla başka bir internet sitesine yönlendirilmesi ve Exxefy'da var olan ve ileride oluşturulabilecek interaktif alanların bu şekilde yetki dışında kullanılması gibi durumlarda hukuki yollara başvurma hakkını saklı tutar.</p>

                            <p><strong>7.7.</strong>&nbsp;Üyeler tarafından gönderilen ve/veya yüklenen İçerikler’den münhasıran söz konusu İçerik’i yükleyen veya gönderen Üye sorumludur. Exxefy, Üyeler tarafından gönderilen ve/veya yüklenen İçerikler’e ilişkin hiçbir sorumluluk üstlenmemektedir. Üyeler Exxefy'ın ve/veya Şirket’in İçerikler’i izlemediğini, ancak bu kuralların ihlal edildiğine veya başka bir nedenle zararlı olduğuna kendi inisiyatifine dayanarak kanaat getirdiği İçerikler dahil olmak üzere, herhangi bir sebeple her türlü İçerik’i inceleme ve kaldırma hakkını saklı tuttuğunu kabul eder.</p>

                            <p><strong>7.8.</strong>&nbsp;Şirket’in herhangi bir talebe veya soruya yanıt verme yükümlülüğü bulunmamaktadır.</p>

                            <p><strong>7.9.</strong>&nbsp;Exxefy'da yer alan bütün yazılı, resimli, sesli, grafik içeren ve/veya içermeyen tablo gibi materyallerin her hakkı saklıdır. Bu materyallerin kopyalanmak suretiyle kişisel sayfalarda yayınlanması ve/veya pazarlanması kesinlikle yasaktır.</p>

                            <p><strong>7.10.</strong>&nbsp;Üyeler, Exxefy'a yükledikleri her türlü İçerik için, Şirket’e söz konusu İçerikler’in Exxefy'da veya çeşitli mecralarda, çeşitli amaçlarla ve çeşitli şekillerde yayınlanmasına ilişkin hakları ve söz konusu İçerikler’i ayrıca bir ücret ödemesi gerekmeksizin herhangi bir form, ortam veya teknolojiye aktarma hakkını, süresiz ve devredilebilir bir hak olarak verirler. Herhangi bir karışıklığa sebep olmamak adına belirtmek gerekir ki; işbu madde kapsamında, Şirket Üyeler tarafından yüklenen Ürünler’in kendilerine ilişkin herhangi bir hak iddia etmemekte, Ürünler’in görüntülerinin Exxefy'da veya çeşitli mecralarda yayınlanması haklarına ilişkin bir bilgilendirme yapılmaktadır.</p>

                            <p><strong>8. GEÇERLİLİK VE DEĞİŞİKLİK</strong></p>

                            <p><strong>8.1.</strong>&nbsp;İşbu Sözleşme; Üye, üyeliği devam ettiği sürece yürürlükte kalacak ve taraflar arasında hüküm ve sonuçlarını doğurmaya devam edecek; Üye’nin üyelik süresinin dolması veya geçici veya kalıcı olarak üyeliğinin durdurulması hallerinde sona ermiş sayılacaktır. Kullanım Koşulları ve diğer metinlerin tamamı işbu Üyelik Sözleşmesi’nin eki ve ayrılmaz bir parçasıdır. Üyelik Sözleşmesi, Kullanım Koşulları ve ekleri Exxefy tarafından güncellenebilir. Üyeler, Exxefy'a her giriş yaptıklarında güncellenmiş hükümleri aynen kabul etmiş sayılacaktır.</p>

                            <p><strong>9. YÜRÜRLÜK</strong></p>

                            <p><strong>9.1</strong>&nbsp;Şirket ile Üye arasında doğacak ihtilaflarda uygulanacak olan hukuk Türkiye Cumhuriyeti hukuku olup ihtilafların çözüm mahalli İstanbul (Merkez) Mahkemeleri ve İcra Daireleridir.</p>

                            <p><strong>9.2</strong>&nbsp;İşbu Üyelik Sözleşmesi, Hizmetler’e ilişkin olarak Exxefy'da yayınlanan tüm metinler işbu Üyelik Sözleşmesi’nin ayrılmaz birer parçası olarak kabul edilen bilcümle uyarı, yazı ve açıklama gibi beyanlarda bildirilen tüm koşullardan, yayınlanan belgelerden ve eklerden oluşan politika belgelerinin tamamı karşılıklı olarak kabul edilerek Üye’nin elektronik olarak onay vermesiyle birlikte yürürlüğe girmiştir.</p>

                            <p><strong>9.3</strong>&nbsp;Şirket herhangi bir zamanda işbu Üyelik Sözleşmesi’nde veya eklerinde yer alan hükümlerden birini, bir kısmını ya da tamamını güncelleyerek üzerinde değişiklik yapma ve yeni halini yayınlama hakkını saklı tutar. Bu kapsamda, yayınlanan metinlerin tamamı Üyeler için yayımı tarihinden itibaren geçerli olacaktır.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
