@extends('layouts.web')
@section('title', 'Kullanım Koşulları - Exxefy')


@section('content')

    <x-pageTitle parentTitle="Politikalar" parentRoute="{{ route('policy.index') }}" title="Kullanım Koşulları" />

    <section class="clearfix">
        <div class="sbst-service-area pd-top-112">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col-xl-12 col-lg-10">
                        <div class="section-title ">

                            <p><strong>Kullanım Koşulları
                            Exxefy’i ilk ziyaretinizden itibaren, aşağıda yazılı olan ve Exxefy’in ziyaret edilmesine ve/veya kullanılmasına ilişkin önemli bilgiler içeren hususları bütünüyle anlamış ve tamamını ayrılmaz bir bütün olarak kabul etmiş sayılırsınız.</strong></p>
                            
                            <p><strong>1. TARAFLAR VE KONU</strong></p>
                            
                            <p><strong>1.1.</strong> İşbu Kullanım Koşulları, Ziyaretçi, Üye, Kullanıcı, Satıcı veya Alıcı olarak Exxefy’e erişim sağlayan kişilerin tamamı için geçerlidir. Bu nedenle lütfen aşağıda yazılı koşulları dikkatlice okuyunuz. Bu koşulları kabul etmiyorsanız Exxefy’i ziyaret etmeyiniz ve/veya kullanmayınız.</p>
                            
                            <p><strong>1.2.</strong> Exxefy’in sahibi Fatih Sultan Mh. Şiir Sk. Relux Plaza No:10 Daire:24 Kat:4 Ümraniye 34771 İstanbul, TÜRKİYE adresinde yerleşik olan Yunus Emre Öztürk Şahıs Şirketi (Bundan böyle kısaca “Şirket” olarak anılacaktır.) adlı şirkettir. Exxefy üzerinden sunulan Hizmetler, Şirket tarafından sağlanmaktadır. Şirket, Exxefy’de yer alan veya alacak olan bilgileri, formları, her neviden içeriği ve işbu Kullanım Koşulları’nı dilediği zaman, ayrıca herhangi bir bildirimde bulunmaksızın değiştirme hakkını saklı tutar.</p>
                            
                            <p><strong>1.3.</strong> Exxefy, işbu Kullanım Koşulları’nda belirtilen koşulları her zaman ve herhangi bir ihbarda veya bildirimde bulunmadan değiştirebilir. Bu değişiklikler, İnternet Sitesi’nde yayımlandığı tarihten itibaren İnternet Sitesi’ni ziyaret eden veya kullanan herkes için geçerli olacaktır. İşbu Kullanım Koşulları Ziyaretçi, Kullanıcı, Satıcı veya Alıcı’nın tek taraflı beyanı ile değiştirilemez.</p>
                            
                            <p><strong>2. TANIMLAR</strong></p>
                            
                            <p><strong>İNTERNET SİTESİ :</strong> Tüm hakları Şirket’e ait olan, www.exxefy.com alan adı ve bu alan adına bağlı alt alan adlarından oluşan, Satıcılar’ın Ürünler’ini satışa sunabilecekleri, Alıcılar’ın ise bu Ürünler’i görüntüleyebilecekleri platform Hizmetleri’nin sunulduğu internet sitesidir.</p>
                            
                            <p><strong>UYGULAMA :</strong> Tüm hakları Şirket’e ait olan, cep telefonu, tablet ve benzeri taşınabilir cihazlarda çalışan mobil uygulama yazılımdır.</p>
                            
                            <p><strong>UYGULAMA MAĞAZASI :</strong> Tüm hakları Şirket’e ait olan, Exxefy üzerinde kullanılmak üzere oluşturulmuş Uygulamaları ve bu Uygulamalar ile bağlantılı olarak oluşturulan ürün ve hizmetlerin listelenerek sunulduğu mecrayı ifade eder. Uygulamalar ücretiz olarak ya da ücretli sunulabilir. Uygulamaların ücretli olması halinde, ücrete ilişkin detaylar ile her bir uygulamanın kullanım koşulları, kuralları ve benzeri kullanıma ilişkin detayları da Uygulama Mağazası’nda ayrıca belirtilecektir.</p>
                            
                            <p><strong>UYGULAMALAR :</strong> Exxefy üzerinde kullanılmak üzere oluşturulmuş yazılımlardır. Uygulamalar Şirket tarafından oluşturulmuş olabileceği gibi, Uygulama Mağazası’nda satışa ve/veya kullanıma sunulmak üzere üçüncü kişiler tarafından geliştirilmiş de olabilir. Uygulamalara ilişkin olarak Şirket tarafından üstlenilen yükümlülükler ve/veya Uygulama’ya ilişkin koşullar, Uygulama’nın Şirket tarafından veya üçüncü kişiler tarafından geliştirilmiş olmasına göre farklılık arz edebilir. Uygulamalara ilişkin detaylı bilgiler, her bir Uygulama’nın ilgili sayfasında ayrıca belirtilecektir.</p>
                            
                            <p><strong>Exxefy :</strong> İnternet Sitesi ve Uygulama birlikte “Exxefy” olarak ifade edilmektedir.</p>
                            
                            <p><strong>HİZMETLER :</strong> Exxefy üzerinden Satıcı ve Alıcılar’ın Kullanım Koşulları ve Üyelik Sözleşmesi’nde tanımlı olan işlemleri gerçekleştirmelerini sağlamak amacıyla Exxefy tarafından sunulan platform sağlama Hizmetler’inin tamamını ifade eder. Bu kapsamda Exxefy üzerinden, Satıcılar tarafından Veritabanı’na yüklenen içeriklerin Ziyaretçiler tarafından görüntülenebilmesi, Ziyaretçiler’in Ürünler’e ulaşabilmesi için Ürünler’in listelenmesi ve satılan Ürünler’in raporlanması Hizmetler’i sağlanmaktadır. Şirket, dilediği zaman ve hiçbir bildirimde bulunmaksızın Hizmetler’in tanımını değiştirebilir, Hizmetler’i üçüncü kişilerin kullanımına kapatabilir.</p>
                            
                            <p><strong>ZİYARETÇİ :</strong> Exxefy’e erişen her gerçek ve tüzel kişiyi ifade eder. Ziyaretçi tanımı, Üye, Kullanıcı, Satıcı ve Alıcı tanımlarının tamamını kapsamaktadır.</p>
                            
                            <p><strong>ÜYE :</strong> Exxefy üzerinde, oluşturduğu hesap ile listelediği ürünler ve/veya hizmetler ile içeriklerini kendileri oluşturarak Ürün satışa sunan ve Üyelik Sözleşmesi’nde belirtilen koşullar dâhilinde Exxefy’e üye olmuş gerçek veya tüzel kişileri ifade eder. Üyeler, bundan böyle “Satıcı” olarak da anılabilecektir.</p>
                            
                            <p><strong>KULLANICI :</strong> Exxefy üzerinden satışa sunulan Ürünler’i satın alan her gerçek ve tüzel kişiyi ifade eder. Kullanıcılar bundan böyle “Alıcı” olarak da anılabilecektir.</p>
                            
                            <p><strong>ÖDEME HİZMET SAĞLAYICI :</strong> Şirket’in sözleşmesel ilişki içinde olduğu 6493 sayılı Ödeme ve Menkul Kıymet Mutabakat Sistemleri, Ödeme Hizmetleri ve Elektronik Para Kuruluşları Hakkında Kanun’un 13. maddesine göre 5411 sayılı Kanun kapsamındaki bankalar, elektronik para kuruluşları ve ödeme kuruluşları ödeme hizmeti sağlayıcılarıdır.</p>
                            
                            <p><strong>ÜRÜN :</strong> Exxefy üzerinden Satıcılar tarafından başta Yasaklı Ürünler listesi olmak üzere Kullanım Koşulları, Üyelik Sözleşmesi ve eklerine uygun olarak satışa sunulan ürün ve hizmetleri ifade eder.</p>
                            
                            <p><strong>İÇERİK :</strong> Exxefy üzerinden erişimi mümkün olan, Şirket veya Satıcılar tarafından yüklenmiş olan Ürünler’e ilişkin bilgiler de dahil olmak ve fakat bununla sınırlı olmamak üzere her türlü bilgi, yazı, dosya, resim, video ve benzeri görsel, yazınsal ve işitsel imgelerlerdir. İçerik, bundan böyle “Ürün” olarak da anılabilecektir.</p>
                            
                            <p><strong>ARAYÜZ :</strong> İçerikler’in Ziyaretçiler tarafından görüntülenebilmesi ve Exxefy Veritabanı’ndan sorgulanabilmesi amacıyla Ziyaretçiler tarafından kullanılan; 5846 sayılı Fikir ve Sanat Eserleri Kanunu (FSEK) kapsamında korunan ve tüm fikri hakları Şirket’e ait olan, Exxefy üzerinden yapılabilecek her türlü işlemin gerçekleştirilmesi için bilgisayar programına komut veren internet sayfalarıdır.</p>
                            
                            <p><strong>VERİTABANI :</strong> İçerikler’in depolandığı, tasnif edildiği, sorgulanabildiği ve erişilebildiği ve mülkiyeti Şirket’e ait olan ve 5846 sayılı Fikir ve Sanat Eserleri Kanunu gereğince korunan veriler bütünü ve bu verilerin okunabilmelerini sağlayan sistemdir.</p>
                            
                            <p><strong>3. EXXEFY KOŞULLARI VE KULLANIMA İLİŞKİN YÜKÜMLÜLÜKLER</strong></p>
                            
                            <p><strong>3.1.</strong> Şirket, Satıcılar’ın Ürünler’ini Exxefy’e yüklemesini ve Ziyaretçiler’in bu Ürünlere ulaşmasına, Ürünler’i satın alma öncesinde görüntülenebilmesini ve Alıcılar’ın Ürünler’i kredi kartı ile veya Şirket tarafından Exxefy’de belirlenen diğer yöntemlerle satın alması Hizmetler’ini sağlamaktadır. Şirket tarafından sunulan Hizmetler’in değiştirilmesi, bu Hizmetler’e yeni hizmetler eklenmesi, bu Hizmetler’in kapsam ve sunulma koşullarının değiştirilmesi yalnızca ve sadece Şirket’in inisiyatifindedir. Şirket, bu yetkisini herhangi bir bildirimde bulunmadan tek taraflı olarak dilediği biçimde ve dilediği zaman kullanabilir.</p>
                            
                            <p><strong>3.2.</strong> Şirket, Veritabanı’na yüklenen bilgilerin Ziyaretçiler tarafından görüntülenmesi esasıyla çalışmaktadır. Şirket, Ziyaretçiler tarafından görüntülenen İçerikler’in hiçbir koşulda doğruluğunu, güvenliğini ve hukuka uygunluğunu garanti etmemekte ve bu İçerikler dolayısıyla hiçbir sorumluluk üstlenmemektedir.</p>
                            
                            <p><strong>3.3.</strong> Hizmetler; (i) Satıcılara, Ürünler’i satışa sunabilecekleri, Alıcılara ise Ürünler’i görüntüleyebilecekleri ve sipariş verebilecekleri bir platform sağlanması ve (ii) Alıcılar tarafından yapılan ödemelerin, ilgili Ürün’ün Alıcı tarafından teslim alınmasını takiben Satıcı’ya aktarılmasının sağlanmasıdır. Exxefy’in, Satıcılar tarafından kargoya teslim edilen Ürünler’in içeriği kontrol etme yükümlülüğü bulunmamaktadır. Bu kapsamda, Satıcı’nın ilgili Ürün’ü Alıcı’ya göndermemesi halinde veya Alıcı tarafından kendisine gönderilen Ürün’ün vaat edilenden farklı, ayıplı, noksan çıkması halinde Alıcı tarafından gönderilen bedel Alıcı’ya iade edilir.</p>
                            
                            <p><strong>3.4.</strong> Exxefy ve bu kapsamda Şirket, 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve 6563 sayılı Elektronik Ticaret Düzenlenmesi Hakkında Kanun kapsamında mesafeli sözleşme kurulmasına aracılık eden ve “Aracı Hizmet Sağlayıcı” sıfatına haizdir.</p>
                            
                            <p><strong>3.5.</strong> Exxefy, Üyeler’in Exxefy üzerinden satışa sundukları Ürünler’in listelenmesi, Alıcılar tarafından Ürünler’in bedelinin ödenmesini, Alıcılar tarafından ödenen bedellerin ilgili Satıcı’ya aktarılmasını sağlamaktadır. Bu kapsamda Satıcılar, Şirket’in Satıcı namına satışa sunulan Ürünler’in bedelini tahsile yetkili olduğunu kabul ve taahhüt ederler. Alıcılar, Exxefy vasıtası ile ödeme yaparak Satıcılar ile kurdukları sözleşme ilişkisi kapsamındaki ödeme yükümlülüklerini ifa etmiş olurlar. Bu kapsamda Satıcı, Şirket’in Alıcılar tarafından yapılacak ödemelerin ilgili Ürün’ün Alıcı tarafından teslim alınmasını takiben Satıcı’nın hesabına aktarılması hususunda yetkili olduğunu ve de Hizmetler karşılığında hizmet bedeli ödemekle yükümlü olacağını, peşinen kabul ve taahhüt eder.</p>
                            
                            <p><strong>3.6.</strong> Exxefy kapsamında, Satıcılar da dahil olmak ve fakat bunlarla sınırlı olmamak üzere, üçüncü kişiler tarafından sağlanan Hizmetler’den ve İçerikler’den dolayı Şirket’in işbirliği içinde bulunduğu gerçek ve tüzel kişilerin, Şirket çalışanlarının ve yöneticilerinin hiçbir şekil ve şart altında hukuki veya cezai sorumluluğu bulunmamaktadır Şirket’in, Exxefy üzerinde Üyeler de dahil olmak üzere üçüncü kişiler tarafından yüklenen her neviden içerikleri denetleme ve kontrol etme yükümlülüğü bulunmamaktadır.</p>
                            
                            <p><strong>3.7.</strong> Üyeler, Kullanıcılar ve Ziyaretçiler, Şirket’in ilgili bölümlerine girilen hiçbir bilgiyi kontrol etmekle yükümlü olmadığını ve kendisine verilen bilgilerin doğruluğunu hiçbir koşul altında taahhüt etmediğini peşinen kabul, beyan ve taahhüt eder. Bununla birlikte Ziyaretçiler, Hizmetlerin talep edilen şekilde verilebilmesi için Exxefy’e kendilerine ait, gerçek ve eksiksiz bilgileri vermekle yükümlü olduklarını; aksi takdirde, Ürünlerin verdikleri adrese ulaşması da dahil olmak, ancak bununla sınırlı olmamak üzere çeşitli sorunların doğabileceğini kabul ederler. Bu kapsamda, Ziyaretçiler Exxefy üzerinden kendilerinden talep edilen bilgileri tam, doğru ve gerçeğe uygun şekilde vermekle yükümlü olup söz konusu bilgileri yanlış vermelerinden dolayı Şirket’in her türlü zararını karşılamakla yükümlüdür.</p>
                            
                            <p><strong>3.8.</strong> Şirket, Satıcılar tarafından Exxefy’e yüklenen, değiştirilen, sağlanan İçerikler’in hukuka uygunluğunu ve üçüncü kişilerin haklarını ihlal edip etmediğini araştırmakla yükümlü ve de sorumlu değildir. Şirket, yüklenen ve/veya sunulan İçerikler’in güvenli, doğru ve hukuka uygun olduğunu taahhüt ve garanti etmez.</p>
                            
                            <p><strong>3.9.</strong> Şirket, 5651 sayılı Kanun ve yürürlükteki diğer ilgili mevzuat uyarınca kendisine getirilen yükümlülüklere uymak amacıyla Ziyaretçiler’in Exxefy üzerinde gerçekleştirdikleri her türlü işleme ilişkin olarak ilgili mevzuatta belirtilen kayıtları yasal süresi içinde kayıt altına almakta ve saklamaktadır.</p>
                            
                            <p><strong>3.10.</strong> Exxefy ile paylaşılan kişisel veriler, 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVKK”) kapsamında işlenmektedir. Kişisel verilerin işlenmesine ilişkin daha fazla bilgi edinmek için lütfen Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni’ni inceleyiniz.</p>
                            
                            <p><strong>3.11.</strong> Şirket, Exxefy üzerinden Alıcılar ve Satıcılar tarafından kendisine iletilen bilgileri kullanabilir, ifşa edebilir, üçüncü kişilerle paylaşabilir, bu bilgileri işleyebilir, paylaşabilir, bir veritabanı üzerinde tasnif edip saklayabilir. Şirket aynı zamanda; Ziyaretçiler’in kimliği, adresi, e-posta adresi, telefonu, IP adresi, Exxefy’in hangi bölümlerini ziyaret ettiği, tarayıcı tipi, işlem tarih gibi bilgileri de istatistiki değerlendirme ve kişiye yönelik hizmetler sunma gibi amaçlarla edinebilir, saklayabilir, kullanabilir, iş ortağı olan üçüncü kişilerle sözleşme ilişkisi kapsamında ve sözleşmenin ifası amacıyla paylaşabilir.</p>
                            
                            <p><strong>3.12.</strong> Ziyaretçiler, Exxefy üzerinde yalnızca hukuka uygun işlemler yapabilirler. Ziyaretçiler’in, Exxefy dâhilinde yaptığı her işlem ve eylemdeki hukuki ve cezai sorumluluk bizzat ve sadece kendilerine aittir.</p>
                            
                            <p><strong>3.13.</strong> Exxefy’deki Ürünler’e ilişkin bilgiler ve ilanlar güncelliğini yitirebilir. Ürünler’e ilişkin bilgileri güncelleme yükümlülüğü münhasıran Satıcılar üzerinde olup Şirket bu konuda herhangi bir güncelleme taahhüdünde bulunmamaktadır.</p>
                            
                            <p><strong>3.14.</strong> 18 yaşından küçük kişiler Exxefy’den alışveriş yapamazlar. Exxefy’de çocuklara yönelik Ürünler satışa sunulabilir; ancak bunlar yetişkinlere satılmaktadır.</p>
                            
                            <p><strong>3.15.</strong> Ziyaretçiler, Exxefy’de yer alan bulunan elektronik metin, görsel ve işitsel imgeler, video klipler, dosyalar, veri tabanlar, kataloglar ve listeler de dahil olmak üzere hiçbir İçerik’i çoğaltmayacağı, kopyalamayacağı, dağıtmayacağı, işlemeyeceğini; gerek bu eylemleri ile gerekse de başka yollarla Şirket ile doğrudan ve/veya dolaylı olarak rekabete girmeyeceğini kabul ve taahhüt etmektedir.</p>
                            
                            <p><strong>3.16.</strong> Ziyaretçiler, Exxefy’de, Şirket’in ve üçüncü kişilerin şahsi ve ticari itibarını sarsacak ya da kişilik haklarına tecavüz edecek fiilleri gerçekleştirmeyeceklerini kabul ve taahhüt ederler.</p>
                            
                            <p><strong>3.17.</strong> Exxefy üzerinden erişilen ve/veya görüntülenen her türlü İçerik’in Şirket’in öncül ve yazılı onayı olmadan üçüncü kişilerce Exxefy dışında başta internet olmak üzere herhangi bir ortamda kullanılamaz ve görüntülenemez; aksi haller hukuka aykırı kullanım teşkil edecektir.</p>
                            
                            <p><strong>3.18.</strong> Exxefy üzerinden erişilen ve/veya görüntülenen İçerik’in depolandığı Veritabanı’na üçüncü kişilerce yalnızca ilgili içeriklerin görüntülenmesi amacıyla ve/veya Şirket’in yazılı olarak izin verdiği şekilde ve kapsamda erişilmesi hukuka uygun olarak kabul edilir. Bunun dışında yapılan erişimler hukuka aykırı olup Şirket’in dava ve takip hakları her zaman için saklıdır.</p>
                            
                            <p><strong>3.19.</strong> Veritabanı ve Veritabanı’nda yer alan bilgilerin tamamı ya da bir kısmı Şirket’in öncül ve yazılı onayı olmadan kopyalanamaz, başka veritabanlarına aktarılamaz ve bu veritabanlarından üçüncü kişilerin erişimine ve kullanımına açılamaz.</p>
                            
                            <p><strong>3.20.</strong> Exxefy üzerinden erişilen ve/veya görüntülenen İçerik’i elde etmek maksadıyla Veritabanı’ndan yoğun şekilde bilgi çekmek yasaktır. Bu yasağa uymayarak Veritabanı’ndan yoğun şekilde bilgi çeken kişilerin, Türk Ceza Kanunu’nun 243/1. maddesi kapsamında ‘ bilişim sistemine yetkisiz giriş yapma’ eylemini gerçekleştirmeleri sebebiyle yürürlükteki mevzuat uyarınca cezalandırılmaları amacıyla Şirket tarafından bu kişiler hakkında suç duyurusunda bulunulacaktır.</p>
                            
                            <p><strong>3.21.</strong> İçerik’in ve Arayüz’ün Şirket’in yazılı rızası olmadan kopyalanması, çoğaltılması, iletilmesi, işlenmesi ve başka internet sitelerinde ve/veya mecralarda görüntülenmesi yasaktır.</p>
                            
                            <p><strong>3.22.</strong> Exxefy üzerinden erişilen ve/veya görüntülenen sayfalarda yer alan kişisel veriler, ilgili kişilerin ve Şirket’in yazılı izni olmaksızın hiçbir koşul ve şart altında üçüncü kişilerce kullanılmaz, işlenemez, iletilemez, görüntülenemez ve ifşa edilemez. Ancak Şirket, yasalar öngördüğü takdirde, yasal merci ve makamların kararları doğrultusunda yürürlükteki yasalar kapsamında kalmak şartıyla ve ilgili kararın çerçevesinde olmak üzere Ziyaretçiler ile ilgili birtakım bilgileri ilgili makam ve mercilere verebilir.</p>
                            
                            <p><strong>3.23.</strong> Şirket, Exxefy üzerinden başka internet sitelerine bağlantılar ve/veya yönlendirmeler sağlayabilir. Bu bağlantıların varlığı, Exxefy dışındaki diğer site ve sayfaların içeriklerinin denetlendiğini göstermez. Bu bağlantılardan erişilebilecek Exxefy dışında kalan içeriklerden dolayı Şirket’in herhangi bir sorumluluğu bulunmadığı gibi, erişilen diğer internet sitelerinde yapılacak işlemlerden doğacak zarardan da Şirket sorumlu değildir. Ziyaretçiler bu bağlantıları kullanarak diğer internet sitelerine eriştiklerinde, sorumluluğun kendilerinde olduğu peşinen kabul ederler.</p>
                            
                            <p><strong>3.24.</strong> Exxefy’e yüklenmiş olan dosyaların içeriğinden yola çıkarak yapılabilecek hiçbir uygulamadan Şirket hukuki ve cezai olarak sorumlu değildir. Bunlardan dolayı doğabilecek maddi ya da manevi, dolaylı ya da doğrudan her neviden zararlardan Şirket ve ona bağlı kişi ve kuruluşlar sorumlu tutulamaz.</p>
                            
                            <p><strong>3.25.</strong> Şirket, Exxefy dahilinde kişisel bilgileri gizli tutmak için gerekli tüm tedbirleri almayı taahhüt eder. Ziyaretçiler, Şirket tarafından alınan gerekli tüm tedbir ve önlemlere rağmen Exxefy’e yapılan her türlü saldırı sonucu kişisel bilgilerin herhangi bir şekilde zarar görmesi veya bunların üçüncü şahısların eline geçmesi durumunda Exxefy’in herhangi bir sorumluluğu bulunmadığını peşinen kabul eder. Ziyaretçiler bu sebeple doğacak zararlardan Şirket’i hiçbir şekilde sorumlu tutmayacaklarını peşinen kabul ve beyan eder.</p>
                            
                            <p><strong>3.26.</strong> Alıcı, Exxefy’de Satıcı’ya ait Ürünler’i Şirket’in sunduğu altyapı ile Exxefy üzerinden yapar. Alıcı’nın satın alma talebi, Ürün’e ilişkin Satıcı tarafından hazırlanan, Şirket ya da Şirket dışındaki platformlardaki sayfalarda belirtilen koşulları kabul ederek Satıcı ile arasında bir satış akdinin Ürün’ü satın alma talebiyle kurulduğu anlamına gelmektedir. Alıcı bu satın alma talebiyle ilgili Ürün’ü satın almayı kabul ve taahhüt eder.</p>
                            
                            <p><strong>3.27.</strong> Alıcılar, Exxefy’de satılan Ürünler’in teklif edildikleri fiyatı, kendilerine sunulan ödeme ekranındaki bilgileri takip etmek sureti ile ödeme bilgilerini vermek suretiyle satın alırlar. Alıcılar, Ürün’ü Exxefy’de belirtilen fiyattan almayı, Satıcı açıkça kabul etmedikçe Ürün’ün fiyatından indirim talep etmeyeceklerini, Exxefy’de ilan edilen ödeme koşullarına aykırı davranmayacaklarını peşinen kabul, beyan ve taahhüt ederler.</p>
                            
                            <p><strong>3.28.</strong> Satın aldığı Ürün’ü kontrol etmekle yükümlü olan Alıcı, teslim aldığı Ürün’ün ayıplı olması halinde, Tüketicinin Korunması Hakkında Kanun’dan kaynaklanan tüm yasal haklarını Satıcı’ya karşı kullanabilir. Alıcı, Şirket’in Ürün’ün satışından, tesliminden ve varsa ayıplarından dolayı hiçbir sorumluluğu bulunmadığını peşinen kabul ve beyan eder.</p>
                            
                            <p><strong>3.29.</strong> Alıcı, Exxefy’den Ürün’ü satın alarak kredi kartı veya Şirket’in belirleyeceği başkaca ödeme yöntemleri ile ödeme yapacaktır. Ürün’ün satın alınmasından doğan para borcunun ifasının Şirket dışındaki platformlardan gerçekleşmesi halinde, Şirket’in Ürün’e, satışına ve teslimine ilişkin hiçbir sorumluluğu bulunmamaktadır. Şirket, kredi kartı ve diğer yöntemlerle yapılan satışlara ilişkin promosyon, reklam ve taksitle ödeme imkanlarını Exxefy’den Alıcı’ya duyurur. Bununla birlikte, Şirket’in bankalar tarafından yapılan promosyon, reklam, taksitle ödeme imkanı gibi ödeme kolaylıkları bakımından hiçbir sorumluluğu yoktur.</p>
                            
                            <p><strong>3.30.</strong> Ürün’e ait kargo bilgileri ve teslimatın takibine ilişkin uyarı, Exxefy tarafından Alıcılar’ın verdikleri e-posta adresine bildirilecektir. Alıcılar’ın Exxefy’deki ilgili bölüme e-posta adreslerini hiç, tam veya gerçeğe uygun şekilde girmemeleri halinde Alıcı, Şirket’in kendisine kargo bilgileri ve Mesafeli Satış Sözleşmesi de dahil olmak ve fakat bunlarla sınırlı olmamak üzere hiçbir bildirimde bulunamayacağını peşinen kabul eder.</p>
                            
                            <p><strong>3.31.</strong> Şirket, Alıcılar’dan Satıcılar adına tahsil edilecek ödemeler dışında, hiçbir koşul altında Alıcılar’ı ve/veya Satıcılar’ı temsil etmemektedir. Şirket’in Satıcı ve Alıcı arasında ortaya çıkabilecek herhangi bir uyuşmazlık ve benzeri durumda Satıcı ve Alıcı arasındaki iletişimi sağlama da dahil olmak üzere herhangi bir yükümlülüğü olmadığı gibi, Satıcı ve Alıcı arasında herhangi bir uyuşmazlık çıkması halinde Şirket, söz konusu uyuşmazlığa ilişkin taraf olarak gösterilemez.</p>
                            
                            <p><strong>3.32.</strong> Ürün’ün teslimatından sonra Alıcı’nın yaptığı ödemenin ilgili banka veya finans kuruluşu tarafından herhangi bir sebeple ödenmemesi, iptali veya Şirket hesaplarından geri çekilmesi hallerinde Ürün teslimi de gerçekleştirilmez ya da gerçekleştirilmişse Alıcı Ürün’ü kullanmadan ve derhal iade etmekle yükümlüdür. Bu takdirde Alıcı, en geç 24 saat içerisinde Ürün’ü Satıcı’nın belirteceği adrese göndermekle yükümlüdür. Alıcı ve Satıcı, Şirket’in bu konuda herhangi bir yükümlülüğü bulunmadığını, bu sebeple Şirket’ten herhangi bir talepte bulunmayacaklarını kabul, beyan ve taahhüt ederler.</p>
                            
                            <p><strong>3.33.</strong> Exxefy; yapılan herhangi bir işleme harcama itirazı bildirimi gelmesi ve/veya ödeme hizmeti sağlayan kuruluşun yapılan işlem aleyhine yapılan itirazı kabul etmesi ve bu kapsamda itirazın kesinleşmesi veyahut da işlemin şüpheli bir işlem olması veyahut da Satıcı’nın işlemleriyle ilgili Exxefy’e Alıcılar’dan birden fazla şikayet ulaşması durumunda; şüpheli işlemlerle ilgili Satıcı’ya Alıcı ve/veya Exxefy tarafından ulaşılamaması, Yasaklı Ürünler Listesi’nde yer alan ürün veya hizmetlerin satışa sunulduğunun tespit edilmesi, söz konusu işlemin Üye’nin genel işlem tutarı ortalamasının üzerinde olması veyahut da işlemin geçerliliği ve hukukiliğine ilişkin herhangi bir nedenle şüphe uyandırması halinde, ilgili işleme ilişkin ödenen ücretin Satıcı’ya aktarılması için Alıcı ve Satıcı’dan ek bilgi ve belgeler talep edebilir. Söz konusu ek bilgi ve belgeler tamamlanıncaya ve/veya Alıcı tarafından yapılan ödeme ilgili işleme ilişkin şüphe ortadan kalkıncaya değin Satıcı’nın hesabına aktarılmayabilir. Bu kapsamda, Alıcı veya Satıcı’dan talep edilen bilgi ve belgelerin Exxefy’e iletilme süresinin dolması durumunda, Alıcı tarafından yapılan ödeme, Exxefy tarafından bloke edilebilir veya ilgili siparişe ilişkin bedelin Alıcı ya da Bankasına iade edilmesi halinde, Exxefy ödediği bedeli Satıcının yapmış olduğu farklı satışlardan mahsup veya tahsil edebilir. Bu hususta karar verme yetkisi yalnızca ve sadece Şirket’e ait olup belirtilen işlem yalnızca Alıcı ve Satıcılar’ın güvenliğini sağlamak maksadıyla kullanılmaktadır.</p>
                            
                            <p><strong>3.34.</strong> Satıcının kargo işlemlerinden doğan herhangi bir borcu bulunması halinde, ilgili borç bakiyesi Exxefy tarafından Alıcının yaptığı ödemeden veya Satıcının farklı siparişlerinden mahsup veya tahsil edilebilir. Bu hususta karar verme yetkisi Şirket’e aittir.</p>
                            
                            <p><strong>3.35.</strong> Alıcı, Satıcılar tarafından satışa arz edilen ürün ve hizmetlerin ayıplı olup olmaması, listelenmesi, satışa arzı Yasaklı Ürünler’den olup olmaması, niteliği, orijinalliği, Ürün’ün tanıtımında kullanılan yazılı ve/veya görüntülü açıklamaların doğruluğu ve tamlığı da dahil olmak üzere Ürün’e ilişkin hiçbir konu hakkında Şirket’in bilgi sahibi olmadığı ve olması gerekmediğini ve bunları taahhüt ve garanti etmek yükümlülüğü bulunmadığını kabul ve beyan eder.</p>
                            
                            <p><strong>3.36.</strong> Üyelik Sözleşmesi, Kullanım Koşulları ve eklerine aykırılık hallerinde Şirket’in maddi ve manevi zararının tazminini talep hakkı saklıdır. Üyelik Sözleşmesi, Kullanım Koşulları ve ekleri Exxefy’in herhangi bir sebeple yayınının durması/durdurulması halinde bu süre boyunca askıda sayılır. Bu süreçte askıda kalan satış işlemleri için Üyeler ve Kullanıcılar bir tazmin talebinde bulunamaz.</p>
                            
                            <p><strong>3.37.</strong> Ziyaretçiler, işbu Kullanım Koşulları, Üyelik Sözleşmesi ve eklerinde sayılan kural ve yükümlülüklere aykırı davranmaları halinde Şirket’in üyeliği sona erdirmek ve Ziyaretçiler’in Exxefy’e girişini engellemek de dahil olmak ve bununla sınırlı olmamak üzere her türlü hakkını saklı tuttuğunu peşinen kabul, beyan ve taahhüt ederler.</p>
                            
                            <p><strong>3.38.</strong> Kullanım Koşulları ve ekleri, Hizmetler’in sona erdirilmesi halinde kendiliğinden yürürlükten kalkar. Şu kadar ki, Şirket işini, ticari ortaklığını ve İnternet Sitesi alan adını da değiştirmeye, aynı faaliyeti başka bir alan adı üzerinden yürütmeye yetkili olup bu değişikliklerin Üyelik Sözleşmesi’ne herhangi bir etkisi olmayacaktır.</p>
                            
                            <p><strong>3.39.</strong> Üyeler tarafından Ürünler üzerinde yapılacak değişiklikler Şirket’in sorumluluğunda değildir. Bu değişiklikler sebebiyle doğabilecek her türlü fikri ve sınai mülkiyet ihlallerinden, bu ihlallerden dolayı üçüncü kişilerin uğrayabileceği her türlü zarardan ve doğabilecek hukuki ve cezai tüm sorumluluklardan ilgili Üye tek başına sorumludur.</p>
                            
                            <p><strong>3.40.</strong> Şirket’e herhangi bir İçerik’e, talebe, soruya yanıt verme yükümlülüğü bulunmamaktadır.</p>
                            
                            <p><strong>3.41.</strong> Şirket, çevrimiçi ya da çevrimdışı konumdaki hiçbir Ziyaretçi’nin davranışlarından sorumlu değildir. Şirket’in, hiçbir koşulda Exxefy’in kullanımı, içeriği, Ziyaretçiler arasındaki çevrimiçi veya çevrimdışı her türlü iletişim ve etkileşimden doğan sonuçlardan kayıp, hasar, zarar, ölüm vs. dahi olsa sorumluluğu bulunmamaktadır. Şirket’in herhangi bir sebeple bu tür eylemler neticesinde uğrayabileceği her tür doğrudan veya dolaylı, maddi veya manevi zararın tazminini talep hakkı saklıdır.</p>
                            
                            <p><strong>3.42.</strong> Şirket, Ziyaretçiler’e ya da onların e-posta adreslerine, ticari ya da reklam amaçlı istek dışı mesaj gönderilmesi, Üyeler’in bu amaçla başka bir internet sitesine yönlendirilmesi ve Exxefy’de var olan ve ileride oluşturulabilecek interaktif alanların bu şekilde yetki dışında kullanılması gibi durumlarda hukuki yollara başvurma hakkını saklı tutar.</p>
                            
                            <p><strong>3.43.</strong> Üyeler’in Uygulama Mağazası’ndan yapacakları her türlü işlem bakımından Uygulama Mağazası Kullanım Koşulları geçerlidir.</p>
                            
                            <p><strong>4. FİKRİ MÜLKİYET HAKLARI</strong></p>
                            
                            <p><strong>4.1.</strong> Exxefy’den erişilen İçerikler ile Üyeler ve Kullanıcılar tarafından sağlanan bilgiler Exxefy’in, Veritabanı’nın, Arayüz’ün, tasarımı, metni, kodları da dahil olmak ve bunlarla sınırlı olmamak üzere tüm elemanları Şirket’e aittir ve/veya Şirket tarafından üçüncü bir kişiden hukuken geçerli bir lisans altında edinilmiştir. İşbu Kullanım Koşulları dâhilinde Şirket tarafından açıkça yetki verilmediği hallerde Şirket’in Exxefy, Veritabanı, Arayüz de dahil olmak ve fakat bunlarla sınırlı olmamak üzere Exxefy’den doğan her türlü hakkı saklıdır.</p>
                            
                            <p><strong>4.2.</strong> Exxefy’de kullanılan ve Üyeler ve Kullanıcılar tarafından Exxefy’e yüklenmemiş olan her türlü resim, grafik, fotoğraf ve benzeri türden İçerik de Şirket’e aittir ya da yasal sahiplerinden izin alınarak kullanılmaktadır. Gerek Şirket tarafından sağlanan bu türden İçerikler’in Ziyaretçiler ve üçüncü kişiler tarafından başka amaçlarla kullanılması ve gerekse Üyeler ve Kullanıcılar tarafından sağlanan İçerikler’in üçüncü kişiler tarafından başka amaçlar için kullanılması Şirket’in öncül ve yazılı onayına bağlıdır ve bu öncül ve yazılı onayın bulunmaması halinde kesinlikle yasaktır. Bu türden içeriğin izinsiz kullanımı, telif hakları ihlallerine, ticari markalarla ilgili hükümlerin ya da yürürlükteki mevzuatın ihlaline yol açabilir. İçerik’in izinsiz kullanılması halinde Şirket, bu İçerik’ten doğan her türlü hakkını kullanma yetkisini haizdir.</p>
                            
                            <p><strong>4.3.</strong> Şirket, hukuka, yasalara, telif haklarına ve kişilik haklarına saygılı olmayı amaç edinmiştir. Bu nedenle de geçerli telif hakkı sahiplerinin belirtilmesi amacıyla, Exxefy içerisinde yer verilen her türden İçerik’e ilişkin olmak üzere, İçerik’in elde edildiği kaynak adı ve site adresi ile içeriğin hangi lisans altında elde edildiğine ilişkin uygun açıklamaya gereken sayfalarda yer verilmiştir. Ziyaretçiler, Hizmetler’i, Şirket’e ait olan bilgileri ve Şirket’in telif haklarına tabi çalışmalarını yeniden satmak, işlemek, paylaşmak, dağıtmak, sergilemek veya üçüncü kişilerin Şirket’in hizmetlerine erişmesi veya kullanmasına izin vermek hakkına sahip değildirler.</p>
                            
                            <p><strong>5. MÜCBİR SEBEPLER</strong></p>
                            
                            <p><strong>5.1.</strong> Hukuken mücbir sebep sayılan tüm durumlarda, Şirket Kullanım Koşulları’ndan ve/veya Üyelik Sözleşmesi’nden ve bu metinlerin Exxefy’de yayınlanan eklerinden doğan yükümlülüklerinden herhangi birisini geç ifa etme ve/veya ifa etmeme nedeniyle hukuken sorumlu değildir. Bu ve bunun gibi durumlar, Şirket açısından, gecikme, ifa etmeme veya temerrüt addedilmeyecek veya bu durumlar için Şirket’in Ziyaretçilerin herhangi bir zararını tazmin yükümlülüğü doğmayacaktır.</p>
                            
                            <p><strong>5.2.</strong> Mücbir sebep terimi, ilgili tarafın makul kontrolü haricinde ve Şirket’in gerekli özeni göstermesine rağmen önleyemediği olaylar olarak yorumlanacaktır. Bunun yanında, bunlarla sınırlı olmamakla birlikte, doğal afet, isyan, savaş, grev, iletişim sorunları, altyapı ve internet arızaları ve/veya kesintileri, elektrik kesintisi ve kötü hava koşulları gibi durumlar da mücbir sebep kapsamında değerlendirilir.</p>
                            
                            <p><strong>6. UYGULANACAK HUKUK</strong>
                            
                            <p>İşbu Kullanım Koşulları’nın uygulanmasında, yorumlanmasında ve bu Kullanım Koşulları dâhilinde doğan hukuki ilişkilerin yönetiminde Türkiye Cumhuriyeti hukuku uygulanacaktır. İşbu Kullanım Koşulları’ndan dolayı doğan veya doğabilecek her türlü ihtilafın hallinde ise İstanbul (Merkez) Mahkemeleri ve İcra Daireleri yetkilidir.</p>
                            
                            <p><strong>7. YÜRÜRLÜK</strong></p>
                            
                            <p>İşbu Kullanım Koşulları, Şirket tarafından Exxefy üzerinden ilan edildiği tarihte tüm Ziyaretçiler için yürürlük kazanır. Ziyaretçiler, işbu Kullanım Koşulları’nı Exxefy’i ziyaret etmekle ve/veya kullanmakla kabul etmiş olurlar. Şirket, dilediği zaman Kullanım Koşulları hükümlerinde değişikliğe gidebilir ve değişiklikler Exxefy üzerinde yayınlandığı tarihte yürürlüğe girer.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection
